#!/usr/bin/env python
"""``runs/latest`` → ``reports/RESULTS.md``. The deliverable is generated, never typed.

Every number in the output is read from a ``metrics.json`` that a command on this machine
produced. There is no template with blanks to fill in by hand, because a template with blanks
is how a placeholder becomes a published number.

The interpretation sentence beneath the comparison table is generated from the McNemar result
too, so it cannot drift from the numbers above it.

Usage
-----
    uv run python evaluate.py -i runs/latest -o reports/RESULTS.md
    uv run python evaluate.py -i runs/run_2 -a runs/run_3 -o reports/RESULTS.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from utils.runs import read_json  # noqa: E402

PRETTY = {
    "tfidf_logreg": "TF-IDF + Logistic Regression (control)",
    "roberta": "RoBERTa (fine-tuned)",
}


def fmt_seconds(seconds: float) -> str:
    total = round(seconds)
    if total < 60:
        return f"{total}s"
    return f"{total // 60}m {total % 60:02d}s"


def fmt_accuracy(block: dict[str, Any]) -> str:
    ci = block["accuracy_ci"]
    half = 100.0 * (ci["high"] - ci["low"]) / 2.0
    return f"**{block['accuracy']:.4f}** [{ci['low']:.4f}, {ci['high']:.4f}] (±{half:.1f} pp)"


def comparison_table(metrics: dict[str, Any]) -> str:
    rows = [
        "| Model | Accuracy (Wilson 95% CI) | Precision (macro) | Recall (macro) | F1 (macro) | Train time | Config |",
        "|---|---|---|---|---|---|---|",
    ]
    order = [k for k in ("roberta", "tfidf_logreg") if k in metrics["models"]]
    for key in order:
        block = metrics["models"][key]
        train_s = block["training"]["train_seconds"] if key == "roberta" else block["train_seconds"]
        rows.append(
            f"| {PRETTY.get(key, key)} | {fmt_accuracy(block)} | "
            f"{block['precision_macro']:.4f} | {block['recall_macro']:.4f} | {block['f1_macro']:.4f} | "
            f"{fmt_seconds(train_s)} ({metrics['device'].upper()}, {metrics['power_mode']}) | "
            f"`cfg/{metrics['config_name']}.yaml` |"
        )
    return "\n".join(rows)


def ablation_table(source: dict[str, Any]) -> str:
    cells = source.get("ablation") or []
    if not cells:
        return ""
    rows = [
        "| Preprocessing | n-grams | Accuracy (Wilson 95% CI) | F1 (macro) | Vocabulary | Fit time | Config |",
        "|---|---|---|---|---|---|---|",
    ]
    for cell in cells:
        pp = cell["preprocessing"]
        chain = (
            "notebook chain (alnum filter + stopwords removed + Porter stem)"
            if pp["REMOVE_STOPWORDS"]
            else "negation preserved (no filter, no stopword removal, no stemming)"
        )
        lo, hi = pp["NGRAM_RANGE"]
        rows.append(
            f"| {chain} | ({lo}, {hi}) | {fmt_accuracy(cell)} | {cell['f1_macro']:.4f} | "
            f"{cell['features']['n_features']:,} | {fmt_seconds(cell['train_seconds'])} | "
            f"`cfg/{source['config_name']}.yaml` |"
        )
    return "\n".join(rows)


def negation_evidence(source: dict[str, Any]) -> str:
    """Show whether negation tokens actually reach the model's strongest features."""
    cells = source.get("ablation") or []
    lines: list[str] = []
    for cell in cells:
        pp = cell["preprocessing"]
        lo, hi = pp["NGRAM_RANGE"]
        neg_features = [
            f["feature"]
            for f in cell["features"]["most_negative"]
            if any(m in f["feature"].split() for m in ("not", "n't", "no", "nor", "never"))
            or f["feature"] in ("not", "n't", "no", "nor", "never")
        ]
        found = (
            ", ".join(f"`{f}`" for f in neg_features[:6])
            if neg_features
            else "*none — deleted before vectorisation*"
        )
        lines.append(f"- **{cell['ablation_label']}** ({lo}, {hi}): {found}")
    if not lines:
        return ""
    return (
        "Negation markers among each cell's 20 most negative coefficients — the direct check "
        "that the preprocessing chain is or is not destroying them:\n\n" + "\n".join(lines)
    )


def build_report(metrics: dict[str, Any], ablation_source: dict[str, Any] | None) -> str:
    cfg_name = metrics["config_name"]
    splits = metrics["splits"]
    sig = metrics.get("significance") or {}
    roberta = metrics["models"].get("roberta")
    control = metrics["models"].get("tfidf_logreg")
    abl = ablation_source or metrics

    parts: list[str] = []
    parts.append("# Results\n")
    parts.append(
        "*Generated by `evaluate.py`. Every number below was read from a `runs/*/metrics.json` "
        "produced by a command on the owner's machine — nothing here is estimated, rounded up, "
        "carried over from the source notebook, or taken from a paper.*\n"
    )

    parts.append("## What produced these numbers\n")
    parts.append(
        f"- **Config** — `{metrics['config_path']}` (`{cfg_name}`)\n"
        f"- **Seed** — `{metrics['seed']}`, single run, single split\n"
        f"- **Splits** — {splits['n_train']:,} train / {splits['n_val']:,} validation / "
        f"{splits['n_test']:,} test\n"
        f"- **Device** — {metrics['device']}, {metrics['power_mode']}\n"
        f"- **Commit** — `{metrics['git_sha']}`\n"
        f"- **Reproduce** — `uv run python train.py -c {metrics['config_path']}` then "
        f"`uv run python evaluate.py -i runs/latest -o reports/RESULTS.md`\n"
    )

    if roberta is not None:
        tr = roberta["training"]
        capped = " **The run was wall-clock capped.**" if tr["wall_clock_capped"] else ""
        parts.append(
            f"The transformer ran {tr['epochs_run']} of {tr['epochs_configured']} configured "
            f"epochs in {fmt_seconds(tr['train_seconds'])}; epoch {tr['selected_epoch']} was "
            f"selected on {tr['selection_criterion']}, and the test set was scored exactly once "
            f"on that checkpoint.{capped}\n"
        )

    parts.append("## Model comparison\n")
    parts.append(comparison_table(metrics) + "\n")
    if sig:
        mc = sig["mcnemar"]
        parts.append(
            f"<sub>seed {metrics['seed']} · n_train {splits['n_train']:,} / n_test "
            f"{splits['n_test']:,} · exact McNemar **p = {mc['p_value']:.4g}** on "
            f"{mc['n_discordant']} discordant pairs · `uv run python train.py -c "
            f"{metrics['config_path']}` · commit `{metrics['git_sha']}`</sub>\n"
        )
        parts.append(f"**{sig['sentence']}**\n")
        parts.append(
            f"The 2×2 discordance table both models were compared on: they agree and are both "
            f"right on {mc['a_both_correct']} examples and both wrong on {mc['d_both_wrong']}; "
            f"RoBERTa alone is right on {mc['b_only_a_correct']} and the control alone is right "
            f"on {mc['c_only_b_correct']}. Only those last two counts carry any information about "
            "which model is better, which is why the effective sample size for the comparison is "
            f"{mc['n_discordant']} and not {splits['n_test']:,}.\n"
        )

    if control is not None and roberta is not None:
        gap = 100.0 * (roberta["accuracy"] - control["accuracy"])
        parts.append("## Reading the control honestly\n")
        parts.append(
            "The TF-IDF + logistic-regression row is a **genuine control, not a formality.** "
            "Amazon Review Polarity is close to linearly separable in bag-of-words space: "
            '"refund", "waste", "flawless" and "returned" are not subtle, and a '
            "well-configured linear model on a few thousand examples is a serious opponent. "
            f"Here it lands {abs(gap):.1f} percentage points "
            f"{'behind' if gap > 0 else 'ahead of'} a fine-tuned 125M-parameter transformer, "
            "at roughly four orders of magnitude less compute.\n"
        )

    abl_table = ablation_table(abl)
    if abl_table:
        parts.append("## Baseline preprocessing ablation\n")
        parts.append(
            "The source notebook's preprocessing chain was: lowercase → keep only `^\\w+$` "
            "tokens → remove NLTK English stopwords → Porter stem, then unigram TF-IDF. That "
            "chain deletes negation twice over. `not`, `no` and `nor` are NLTK English "
            "stopwords, and the `^\\w+$` filter destroys contractions such as `n't` *before* the "
            "stopword filter even runs. With `ngram_range=(1,1)` no bigram can recover the "
            'structure, so `"not good"` and `"good"` collapse to the same feature vector — on '
            "the one task where negation decides the label.\n"
        )
        parts.append(
            "This grid measures what that costs. All four cells were run on the same splits, "
            "and all four are published whatever they show.\n"
        )
        parts.append(abl_table + "\n")
        cells = abl.get("ablation") or []
        if len(cells) >= 4:
            worst = min(cells, key=lambda c: c["accuracy"])
            best = max(cells, key=lambda c: c["accuracy"])
            spread = 100.0 * (best["accuracy"] - worst["accuracy"])
            overlap = worst["accuracy_ci"]["high"] >= best["accuracy_ci"]["low"]
            parts.append(
                f"Spread across the grid: **{spread:.1f} percentage points**, from "
                f"{worst['accuracy']:.4f} (*{worst['ablation_label']}*) to {best['accuracy']:.4f} "
                f"(*{best['ablation_label']}*). The two Wilson intervals "
                f"{'overlap, so on this test set the difference is not resolvable' if overlap else 'do not overlap'}"
                ".\n"
            )
        ev = negation_evidence(abl)
        if ev:
            parts.append(ev + "\n")

    if roberta is not None:
        parts.append("## Training and validation\n")
        parts.append(
            "| Epoch | Train loss | Validation loss | Validation accuracy | Wall clock |\n"
            "|---|---|---|---|---|"
        )
        for h in roberta["training"]["history"]:
            parts.append(
                f"| {int(h['epoch'])} | {h['train_loss']:.4f} | {h['val_loss']:.4f} | "
                f"{h['val_accuracy']:.4f} | {fmt_seconds(h['epoch_seconds'])} |"
            )
        parts.append("")
        parts.append(
            "The source notebook had no validation split, which is why its choice of 5 epochs "
            "was unjustifiable: there was nothing to early-stop on, and selecting an epoch by "
            "test accuracy would have been leakage dressed up as model selection.\n"
        )
        trunc = roberta.get("truncation_test", {})
        if trunc:
            parts.append(
                f"Sequence truncation, measured rather than assumed: at `max_len` "
                f"{int(trunc['max_len'])}, **{100 * trunc['frac_truncated']:.1f}%** of test "
                f"reviews are truncated (median {int(trunc['median_tokens'])} tokens, "
                f"p95 {int(trunc['p95_tokens'])}, max {int(trunc['max_tokens'])}).\n"
            )

    parts.append("## Figures\n")
    parts.append(
        "All regenerable with `make figures`, which reads `runs/latest`. None hand-exported.\n"
    )
    for name, alt in (
        ("confusion_matrix_roberta", "RoBERTa confusion matrix"),
        ("confusion_matrix_baseline", "TF-IDF control confusion matrix"),
        ("training_curves", "Train and validation loss per epoch"),
        ("baseline_ablation", "Preprocessing ablation"),
        ("attention_heatmap", "Last-layer attention heatmap"),
        ("attention_from_token", "Per-token attention"),
        ("saliency_positive", "Gradient saliency, positive reviews"),
        ("saliency_negative", "Gradient saliency, negative reviews"),
    ):
        parts.append(f"- [`docs/images/{name}.png`](../docs/images/{name}.png) — {alt}")
    parts.append("")

    parts.append("## What these numbers do not support\n")
    parts.append(
        f"- A {splits['n_test']:,}-example test set gives a Wilson interval of roughly "
        f"±1.5 percentage points at these accuracies. Gaps smaller than that are not resolvable "
        "here, whatever the point estimates look like.\n"
        f"- {splits['n_train']:,} training rows is a small fraction of the 3.6M available. These "
        "results are about this data scale and do not transfer to full-data training.\n"
        "- One seed, one split. There is no repeated-CV variance estimate, so the run-to-run "
        "standard deviation is unknown rather than small.\n"
        "- MPS fp32 only, no mixed precision, no `torch.compile`. The timings are not comparable "
        "to published CUDA figures.\n"
    )
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("-i", "--run-dir", type=Path, default=REPO_ROOT / "runs" / "latest")
    ap.add_argument(
        "-a",
        "--ablation-run-dir",
        type=Path,
        default=None,
        help="run dir holding the ablation cells, if a different run produced them",
    )
    ap.add_argument("-o", "--out", type=Path, default=REPO_ROOT / "reports" / "RESULTS.md")
    args = ap.parse_args(argv)

    metrics = read_json(args.run_dir.resolve() / "metrics.json")
    ablation = (
        read_json(args.ablation_run_dir.resolve() / "metrics.json")
        if args.ablation_run_dir
        else None
    )

    report = build_report(metrics, ablation)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(f"==> {args.out}  ({len(report.splitlines())} lines)")
    print(f"    config     {metrics['config_name']}")
    print(f"    accuracy   {metrics['accuracy']:.4f}  ({metrics['headline_model']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
