#!/usr/bin/env python
"""THE figure generator. Every PNG in ``docs/images/`` comes from this file.

Nothing in this repo is hand-exported: if a figure cannot be regenerated by one command it
does not ship. ``make figures`` runs this against the explicit published run.

Eight figures:

===============================  ============================================================
``confusion_matrix_baseline``    TF-IDF + LogReg, counts and row-normalised side by side
``confusion_matrix_roberta``     fine-tuned RoBERTa, same layout
``training_curves``              per-epoch train and **validation** loss (justifies D4)
``attention_heatmap``            last-layer head-mean attention, inner tokens only
``attention_from_token``         what one chosen source token attends to
``saliency_positive``            gradient-norm saliency, 3 positive reviews, post-D1-fix
``saliency_negative``            gradient-norm saliency, 3 negative reviews, post-D1-fix
``baseline_ablation``            the 2x2 preprocessing grid
===============================  ============================================================

Every caption names the model and the config that produced it, because a figure whose
provenance is unstated is indistinguishable from a figure taken from somewhere else.

The interpretability figures need live weights, so they are regenerated by re-fitting on the
run's own seed and config. When the checkpoint saved by ``train.py`` is present it is loaded
instead, with no retraining. Pass ``--skip-model-figures`` to produce only the metric figures.

Usage
-----
    uv run python scripts/export_figures.py -i runs/run_2 -a runs/run_3 -o docs/images
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any, cast

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from utils import plots  # noqa: E402
from utils.runs import read_json  # noqa: E402

#: The exact review positions the source notebook hand-picked, so the notebook and the README
#: discuss the same six examples. Positions are into the run's test split.
NOTEBOOK_REVIEW_POSITIONS = (5, 7, 9, 11, 13, 16)

CLASS_LABELS = ("negative", "positive")
EXPECTED_FIGURES = {
    "attention_from_token.png",
    "attention_heatmap.png",
    "baseline_ablation.png",
    "confusion_matrix_baseline.png",
    "confusion_matrix_roberta.png",
    "saliency_negative.png",
    "saliency_positive.png",
    "training_curves.png",
}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _fig_confusion(matrix: np.ndarray, title: str, caption_text: str) -> Any:
    import matplotlib.pyplot as plt

    counts = np.asarray(matrix, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        normed = counts / counts.sum(axis=1, keepdims=True)
    normed = np.nan_to_num(normed)

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.7))
    for ax, data, fmt, sub, vmax in (
        (axes[0], counts, "{:.0f}", "counts", counts.max()),
        (axes[1], normed, "{:.3f}", "row-normalised (recall)", 1.0),
    ):
        im = ax.imshow(data, cmap="Blues", vmin=0, vmax=vmax)
        ax.set_xticks([0, 1], labels=[f"pred {c}" for c in CLASS_LABELS])
        ax.set_yticks([0, 1], labels=[f"true {c}" for c in CLASS_LABELS])
        ax.set_title(sub, fontsize=10, fontweight="normal")
        ax.grid(visible=False)
        for i in range(2):
            for j in range(2):
                shade = data[i, j] / (vmax if vmax else 1)
                ax.text(
                    j,
                    i,
                    fmt.format(data[i, j]),
                    ha="center",
                    va="center",
                    fontsize=11,
                    color="white" if shade > 0.55 else "#111111",
                )
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(title, fontsize=12, fontweight="bold")
    plots.caption(axes[0], caption_text)
    fig.tight_layout()
    return fig


def figure_confusion_matrices(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    written: list[Path] = []
    cfg_name = metrics["config_name"]
    pretty = {
        "tfidf_logreg": "TF-IDF + Logistic Regression (control)",
        "roberta": "RoBERTa (fine-tuned)",
    }
    filename = {"tfidf_logreg": "confusion_matrix_baseline", "roberta": "confusion_matrix_roberta"}
    for key, block in metrics["models"].items():
        if key not in filename:
            continue
        acc = block["accuracy"]
        ci = block["accuracy_ci"]
        fig = _fig_confusion(
            np.asarray(block["confusion_matrix"]),
            pretty[key],
            f"{pretty[key]} · cfg/{cfg_name}.yaml · n_test={block['n_test']} · "
            f"accuracy {acc:.4f} (Wilson 95% CI {ci['low']:.4f}-{ci['high']:.4f}) · "
            f"seed {metrics['seed']} · {metrics['device']}",
        )
        plots.set_provenance(
            fig,
            {
                "accuracy": acc,
                "accuracy_ci": ci,
                "config_name": cfg_name,
                "confusion_matrix": block["confusion_matrix"],
                "model": key,
                "n_test": block["n_test"],
                "seed": metrics["seed"],
            },
        )
        written += plots.save_figure(fig, filename[key], out_dirs)
    return written


def figure_training_curves(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    import matplotlib.pyplot as plt

    block = metrics["models"].get("roberta")
    if not block:
        return []
    history = block["training"]["history"]
    if not history:
        return []

    epochs = [h["epoch"] for h in history]
    train = [h["train_loss"] for h in history]
    val = [h["val_loss"] for h in history]
    val_acc = [h["val_accuracy"] for h in history]
    epoch_ticks = [int(epoch) for epoch in epochs]

    fig, (ax, ax2) = plt.subplots(
        2,
        1,
        figsize=(9.0, 5.8),
        sharex=True,
        gridspec_kw={"height_ratios": [2.35, 1.0]},
    )
    ax.plot(
        epochs,
        train,
        marker="o",
        markersize=5.5,
        linestyle="-",
        linewidth=1.8,
        label="training loss",
        color=plots.OKABE_ITO[0],
    )
    ax.plot(
        epochs,
        val,
        marker="s",
        markersize=5.5,
        linestyle="--",
        linewidth=1.8,
        label="validation loss",
        color=plots.OKABE_ITO[1],
    )
    selected = block["training"]["selected_epoch"]
    ax.axvline(selected, linestyle="-.", linewidth=1.2, color="#555555")
    ax2.axvline(selected, linestyle="-.", linewidth=1.2, color="#555555")
    criterion = block["training"]["selection_criterion"]
    criterion_label = "lowest validation loss" if criterion == "min validation loss" else criterion
    ax.text(
        selected + 0.06,
        0.08,
        f"selected: {criterion_label}",
        transform=ax.get_xaxis_transform(),
        fontsize=8,
        color="#333333",
        ha="left",
        va="center",
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.88, "pad": 1.5},
    )
    ax.set_ylabel("loss (cross entropy)")
    ax.legend(loc="upper right")

    ax2.plot(
        epochs,
        val_acc,
        marker="^",
        markersize=5.0,
        linestyle=":",
        linewidth=1.5,
        color=plots.OKABE_ITO[2],
    )
    ax2.set_xlabel("training epoch")
    ax2.set_ylabel("validation accuracy")
    ax2.set_xticks(epoch_ticks)

    run = block["training"]
    fig.suptitle("Validation loss rose after epoch 1", fontsize=13, fontweight="bold")
    plots.caption(
        ax,
        f"cfg/{metrics['config_name']}.yaml · {block['n_train']} train / {block['n_val']} val · "
        f"seed {metrics['seed']} · {metrics['device']}, {metrics['power_mode']} · "
        f"epochs run {run['epochs_run']}/{run['epochs_configured']}"
        + (" · WALL-CLOCK CAPPED" if run["wall_clock_capped"] else "")
        + f" · epoch selected on {run['selection_criterion']}",
    )
    plots.set_provenance(
        fig,
        {
            "config_name": metrics["config_name"],
            "history": history,
            "model": "roberta",
            "seed": metrics["seed"],
            "selected_epoch": selected,
        },
    )
    fig.tight_layout(rect=(0, 0.03, 1, 0.96), h_pad=1.0)
    with plt.rc_context({"savefig.dpi": 160}):
        return plots.save_figure(fig, "training_curves", out_dirs)


def figure_baseline_ablation(
    metrics: dict[str, Any], out_dirs: list[Path], ablation_metrics: dict[str, Any] | None = None
) -> list[Path]:
    import matplotlib.pyplot as plt

    source = ablation_metrics or metrics
    cells = source.get("ablation") or []
    if not cells:
        return []

    labels = [c["ablation_label"] for c in cells]
    accs = [c["accuracy"] for c in cells]
    lows = [c["accuracy_ci"]["low"] for c in cells]
    highs = [c["accuracy_ci"]["high"] for c in cells]
    errs = np.array(
        [
            [a - lo for a, lo in zip(accs, lows, strict=True)],
            [hi - a for a, hi in zip(accs, highs, strict=True)],
        ]
    )
    colors = [plots.OKABE_ITO[1] if "notebook" in label else plots.OKABE_ITO[0] for label in labels]

    fig, ax = plt.subplots(figsize=(8.6, 3.9))
    y = np.arange(len(labels))
    ax.barh(
        y,
        accs,
        xerr=errs,
        color=colors,
        height=0.62,
        error_kw={"ecolor": "#444444", "capsize": 3, "lw": 1},
    )
    ax.set_yticks(y, labels=labels)
    ax.invert_yaxis()
    ax.set_xlabel("test accuracy (Wilson 95% CI)")
    roberta = metrics["models"].get("roberta")
    show_roberta = bool(roberta) and not roberta.get("random_weights", False)
    # The transformer reference line is the point of comparison, so the x-range has to
    # include it. Otherwise the axvline is drawn off-chart and silently disappears.
    right = max(highs) + 0.035
    if show_roberta:
        right = max(right, roberta["accuracy"] + 0.02)
    ax.set_xlim(max(0.0, min(lows) - 0.02), min(1.0, right))
    ax.grid(visible=True, axis="x", alpha=0.25)
    ax.grid(visible=False, axis="y")
    # Anchor the value label past the upper whisker, not at the bar end. The bar end is exactly
    # where the error bar is centred, so a label placed there covers its own whisker.
    for yi, a, high in zip(y, accs, highs, strict=True):
        ax.annotate(
            f"{a:.4f}",
            xy=(high, float(yi)),
            xytext=(5, 0),
            textcoords="offset points",
            ha="left",
            va="center",
            fontsize=9,
        )

    if show_roberta:
        ax.axvline(roberta["accuracy"], ls="--", lw=1.4, color="#111111")
        ax.annotate(
            f"fine-tuned RoBERTa\n{roberta['accuracy']:.4f}",
            xy=(roberta["accuracy"], 0.0),
            xytext=(-6, 0),
            textcoords="offset points",
            fontsize=8,
            ha="right",
            va="center",
            color="#111111",
        )

    ax.set_title("TF-IDF control: what conventional preprocessing costs")
    plots.caption(
        ax,
        f"TF-IDF + LogReg · cfg/{source['config_name']}.yaml · "
        f"n_train={cells[0]['n_train']} / n_test={cells[0]['n_test']} · seed {source['seed']} · "
        "orange = the source notebook's chain (alphanumeric-only filter + NLTK stopword removal "
        "+ Porter stemming), which deletes not/no/nor and every contraction",
    )
    plots.set_provenance(
        fig,
        {
            "ablation": [
                {
                    "accuracy": cell["accuracy"],
                    "accuracy_ci": cell["accuracy_ci"],
                    "label": cell["ablation_label"],
                }
                for cell in cells
            ],
            "config_name": source["config_name"],
            "roberta_accuracy": roberta["accuracy"] if show_roberta else None,
            "seed": source["seed"],
        },
    )
    fig.tight_layout()
    return plots.save_figure(fig, "baseline_ablation", out_dirs)


# ── model-dependent figures ──────────────────────────────────────────────────────────


def _load_model_for_figures(run_dir: Path, metrics: dict[str, Any]) -> Any:
    """Rebuild the run's transformer and load its saved weights."""
    import torch

    from cfg.schema import load_config
    from models.registry import create_model
    from models.roberta import RobertaSentiment
    from utils.device import resolve_device

    cfg = load_config(REPO_ROOT / metrics["config_path"])
    device = resolve_device(cfg.RUNTIME.DEVICE)
    # Narrowed to the concrete type: the figures need the raw nn.Module and the tokenizer,
    # neither of which belongs on the model-comparison Protocol.
    model = cast(
        RobertaSentiment,
        create_model(
            "roberta",
            pretrained=cfg.MODEL.PRETRAINED,
            revision=cfg.MODEL.REVISION,
            num_labels=cfg.MODEL.NUM_LABELS,
            max_len=cfg.MODEL.MAX_LEN,
            batch_size=cfg.MODEL.BATCH_SIZE,
            epochs=cfg.MODEL.EPOCHS,
            lr=cfg.MODEL.LR,
            seed=cfg.SEED,
            device=device,
            random_weight_layers=cfg.MODEL.RANDOM_WEIGHT_LAYERS,
        ),
    )
    ckpt = run_dir / "model_roberta.pt"
    if not ckpt.exists():
        raise FileNotFoundError(
            f"{ckpt} not found; interpretability figures need the run's weights. "
            "Re-run train.py, or pass --skip-model-figures."
        )
    state = torch.load(ckpt, map_location=device, weights_only=True)
    model.model.load_state_dict(state)
    model.model.eval()
    return model, cfg, device


def _example_texts(run_dir: Path) -> Any:
    import pandas as pd

    return pd.read_parquet(run_dir / "predictions.parquet")


def figure_attention(
    model: Any, cfg: Any, device: Any, text: str, metrics: dict[str, Any], out_dirs: list[Path]
) -> list[Path]:
    import matplotlib.pyplot as plt

    from interpretability.attention import last_layer_attention, pick_source_token

    amap = last_layer_attention(
        model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
    )
    # Keep the heatmap legible: the first 32 inner tokens, which is where the signal is.
    k = min(32, len(amap.tokens))
    tokens = [t.lstrip("Ġ") for t in amap.tokens[:k]]
    matrix = amap.matrix[:k, :k]

    fig, ax = plt.subplots(figsize=(8.6, 7.2))
    im = ax.imshow(matrix, cmap="magma", aspect="auto")
    ax.set_xticks(range(k), labels=tokens, rotation=90, fontsize=7)
    ax.set_yticks(range(k), labels=tokens, fontsize=7)
    ax.set_xlabel("attended-to token (key)")
    ax.set_ylabel("attending token (query)")
    ax.grid(visible=False)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03, label="attention weight")
    ax.set_title(f"Last-layer attention (layer {amap.layer}, mean over {amap.n_heads} heads)")
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · first {k} inner tokens "
        f"(<s>/</s>/<pad> excluded, since <s> is an attention sink and flattens the colour scale) · "
        f"predicted {CLASS_LABELS[amap.predicted_label]} · eager attention (sdpa returns no "
        "attentions at all on transformers 5.x) · attention is not causal explanation",
    )
    shared_provenance = {
        "checkpoint_sha256": metrics["_checkpoint_sha256"],
        "config_name": metrics["config_name"],
        "method": "last_layer_head_mean_attention",
        "model": "roberta",
        "run_git_sha": metrics["git_sha"],
        "seed": metrics["seed"],
        "source_row_position": NOTEBOOK_REVIEW_POSITIONS[0],
    }
    plots.set_provenance(fig, shared_provenance)
    fig.tight_layout()
    written = plots.save_figure(fig, "attention_heatmap", out_dirs)

    idx = pick_source_token(amap, preferred=("not", "great", "bad", "good", "no"))
    row = amap.row_for(idx)
    order = np.argsort(-row)[: min(15, row.size)]
    fig2, ax2 = plt.subplots(figsize=(8.6, 3.6))
    ax2.bar(
        range(len(order)),
        row[order],
        color=plots.OKABE_ITO[0],
    )
    ax2.set_xticks(
        range(len(order)),
        labels=[amap.tokens[i].lstrip("Ġ") for i in order],
        rotation=60,
        ha="right",
    )
    ax2.set_ylabel("attention weight")
    ax2.set_xlabel("attended-to token")
    ax2.set_title(f"What '{amap.tokens[idx].lstrip('Ġ')}' attends to (top {len(order)})")
    plots.caption(
        ax2,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · source token "
        f"'{amap.tokens[idx].lstrip('Ġ')}' · last layer, head-mean · same review as the heatmap",
    )
    plots.set_provenance(fig2, shared_provenance)
    fig2.tight_layout()
    written += plots.save_figure(fig2, "attention_from_token", out_dirs)
    return written


def figure_saliency(
    model: Any,
    cfg: Any,
    device: Any,
    examples: list[tuple[str, int]],
    label_name: str,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    import matplotlib.pyplot as plt

    from interpretability.saliency import gradient_saliency

    n = len(examples)
    fig, axes = plt.subplots(n, 1, figsize=(9.0, 2.5 * n))
    axes_list = list(np.atleast_1d(axes))
    for ax, (text, true_label) in zip(axes_list, examples, strict=True):
        attr = gradient_saliency(
            model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
        )
        keep = [i for i, t in enumerate(attr.tokens) if t not in {"<s>", "</s>", "<pad>"}]
        keep = keep[: min(26, len(keep))]
        toks = [attr.tokens[i].lstrip("Ġ") for i in keep]
        vals = attr.scores[keep]
        ax.bar(
            range(len(toks)),
            vals,
            color=plots.POSITIVE_COLOR if attr.predicted_label == 1 else plots.NEGATIVE_COLOR,
        )
        ax.set_xticks(range(len(toks)), labels=toks, rotation=60, ha="right", fontsize=7)
        # Short enough to stay inside its own panel: a longer label is centred over a 2.5in
        # axis and runs into the rotated tick labels of the panel above it. The quantity is
        # named in full in the figure title and the caption.
        ax.set_ylabel("Token importance", fontsize=9)
        ax.set_title(
            f"true {CLASS_LABELS[true_label]} · predicted {CLASS_LABELS[attr.predicted_label]}"
            f"{'' if attr.predicted_label == true_label else '  ← MISCLASSIFIED'}",
            fontsize=10,
            fontweight="normal",
        )
    fig.suptitle(f"Gradient-norm saliency: {label_name} reviews", fontsize=12, fontweight="bold")
    plots.caption(
        axes_list[-1],
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · gradient of the predicted-class "
        "logit w.r.t. the WORD embeddings only (the D1 fix: the notebook re-applied the full "
        "embedding module, adding position/token-type/LayerNorm twice) · this is gradient-norm "
        "saliency, NOT Grad-CAM, and it satisfies none of Integrated Gradients' axioms",
    )
    plots.set_provenance(
        fig,
        {
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "example_count": len(examples),
            "label": label_name,
            "method": "gradient_norm_saliency",
            "model": "roberta",
            "run_git_sha": metrics["git_sha"],
            "seed": metrics["seed"],
        },
    )
    fig.tight_layout()
    fig.subplots_adjust(hspace=0.75)
    slug = "saliency_positive" if label_name == "positive" else "saliency_negative"
    return plots.save_figure(fig, slug, out_dirs)


def _preflight(
    run_dir: Path,
    metrics: dict[str, Any],
    ablation_run_dir: Path | None,
    *,
    skip_model_figures: bool,
) -> dict[str, Any] | None:
    """Validate every required input before the first PNG can be written."""
    if skip_model_figures:
        return (
            read_json(ablation_run_dir / "metrics.json") if ablation_run_dir is not None else None
        )

    for required in ("model_roberta.pt", "predictions.parquet"):
        path = run_dir / required
        if not path.is_file():
            raise FileNotFoundError(
                f"{path} not found; a complete eight-figure export requires the published "
                "checkpoint and paired predictions"
            )
    roberta = metrics.get("models", {}).get("roberta")
    if not roberta or not roberta.get("training", {}).get("history"):
        raise ValueError(
            f"{run_dir / 'metrics.json'} has no fine-tuned RoBERTa training history; "
            "refusing to produce a partial publication set"
        )
    if ablation_run_dir is None:
        raise ValueError(
            "a complete eight-figure export requires --ablation-run-dir "
            "(the published target uses runs/run_3)"
        )
    ablation_path = ablation_run_dir / "metrics.json"
    if not ablation_path.is_file():
        raise FileNotFoundError(
            f"{ablation_path} not found; the baseline ablation figure cannot be generated"
        )
    ablation_metrics = read_json(ablation_path)
    if len(ablation_metrics.get("ablation") or []) != 4:
        raise ValueError(
            f"{ablation_path} does not contain the required four-cell ablation; "
            "refusing to produce a partial publication set"
        )
    return ablation_metrics


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("-i", "--run-dir", type=Path, default=REPO_ROOT / "runs" / "latest")
    ap.add_argument("-o", "--out-dir", type=Path, default=REPO_ROOT / "docs" / "images")
    ap.add_argument(
        "-a",
        "--ablation-run-dir",
        type=Path,
        default=None,
        help="run dir holding the ablation cells, if a different run produced them",
    )
    ap.add_argument("--skip-model-figures", action="store_true", help="metric figures only")
    ap.add_argument(
        "--publish",
        action="store_true",
        help="also mirror the requested output into tracked reports/figures (explicit opt-in)",
    )
    ap.add_argument("--show", action="store_true", help="also display interactively (never in CI)")
    args = ap.parse_args(argv)

    run_dir = args.run_dir.resolve()
    metrics = read_json(run_dir / "metrics.json")
    ablation_run_dir = args.ablation_run_dir.resolve() if args.ablation_run_dir else None
    ablation_metrics = _preflight(
        run_dir,
        metrics,
        ablation_run_dir,
        skip_model_figures=args.skip_model_figures,
    )
    out_dirs = [args.out_dir.resolve()]
    if args.publish:
        publication_dir = (REPO_ROOT / "reports" / "figures").resolve()
        if publication_dir not in out_dirs:
            out_dirs.append(publication_dir)

    plots.apply_style()
    if args.show:  # pragma: no cover - interactive only
        plots.enable_interactive()

    written: list[Path] = []
    written += figure_confusion_matrices(metrics, out_dirs)
    written += figure_training_curves(metrics, out_dirs)
    written += figure_baseline_ablation(metrics, out_dirs, ablation_metrics)

    if not args.skip_model_figures:
        model, cfg, device = _load_model_for_figures(run_dir, metrics)
        model_metrics = {
            **metrics,
            "_checkpoint_sha256": _sha256(run_dir / "model_roberta.pt"),
        }
        frame = _example_texts(run_dir)
        positions = [p for p in NOTEBOOK_REVIEW_POSITIONS if p < len(frame)]
        rows = [(str(frame["text"].iloc[p]), int(frame["label"].iloc[p])) for p in positions]
        positives = [r for r in rows if r[1] == 1][:3]
        negatives = [r for r in rows if r[1] == 0][:3]
        # Backfill from the split if the notebook's six positions are lopsided in this run.
        for want, bucket in ((1, positives), (0, negatives)):
            i = 0
            while len(bucket) < 3 and i < len(frame):
                if int(frame["label"].iloc[i]) == want:
                    candidate = (str(frame["text"].iloc[i]), want)
                    if candidate not in bucket:
                        bucket.append(candidate)
                i += 1

        written += figure_attention(model, cfg, device, rows[0][0], model_metrics, out_dirs)
        written += figure_saliency(
            model, cfg, device, positives, "positive", model_metrics, out_dirs
        )
        written += figure_saliency(
            model, cfg, device, negatives, "negative", model_metrics, out_dirs
        )

    unique_names = sorted({p.name for p in written})
    if not args.skip_model_figures and set(unique_names) != EXPECTED_FIGURES:
        missing = sorted(EXPECTED_FIGURES - set(unique_names))
        extra = sorted(set(unique_names) - EXPECTED_FIGURES)
        raise RuntimeError(
            f"figure export was incomplete: missing={missing or 'none'}, extra={extra or 'none'}"
        )
    print(f"==> wrote {len(unique_names)} distinct figures into {len(out_dirs)} directories")
    for name in unique_names:
        print(f"    {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
