#!/usr/bin/env python
"""THE figure generator. Every PNG in ``docs/images/`` comes from this file.

Nothing in this repo is hand-exported: if a figure cannot be regenerated by one command it
does not ship. ``make figures`` runs this against the explicit published run.

Eleven figures:

===============================  ============================================================
``confusion_matrix_baseline``    TF-IDF + LogReg, counts and row-normalised side by side
``confusion_matrix_roberta``     fine-tuned RoBERTa, same layout
``training_curves``              per-epoch train and **validation** loss (justifies D4)
``attention_heatmap``            last-layer head-mean attention, inner tokens only
``attention_from_token``         what one chosen source token attends to
``saliency_positive``            gradient-norm saliency, 3 positive reviews, post-D1-fix
``saliency_negative``            gradient-norm saliency, 3 negative reviews, post-D1-fix
``baseline_ablation``            the 2x2 preprocessing grid
``embedding_space_3d``           final-layer [CLS] under t-SNE, errors marked
``layer_probe_accuracy``         linear-probe accuracy against hidden-state index
``attention_entropy_atlas``      mean entropy of all 12x12 heads over the test set
===============================  ============================================================

Every caption names the model and the config that produced it, because a figure whose
provenance is unstated is indistinguishable from a figure taken from somewhere else.

The default publication path regenerates every figure from committed review-text-free evidence.
``--write-model-evidence`` performs forward passes on an existing checkpoint and records the
lower-level arrays; it never refits the transformer. Pass ``--skip-model-figures`` to produce only
the metric figures.

``layer_probe_accuracy`` additionally needs the run's TRAIN rows, which live in the source
parquet rather than in the run directory: a probe fitted on the same rows it is scored on
would measure memorisation. The split is rebuilt from the run's own config and seed, and the
rebuilt test split is asserted identical to ``predictions.parquet`` before anything is fitted.

Usage
-----
    uv run python scripts/export_figures.py -i runs/run_2 -a runs/run_3 -o docs/images
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any, cast

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from utils import plots  # noqa: E402
from utils.runs import read_json  # noqa: E402

#: The exact review positions the source notebook hand-picked, so the notebook and the README
#: discuss the same six examples. Positions are into the run's test split.
NOTEBOOK_REVIEW_POSITIONS = (5, 7, 9, 11, 13, 16)

CLASS_LABELS = ("negative", "positive")
EXPECTED_FIGURES = {
    "attention_entropy_atlas.png",
    "attention_from_token.png",
    "attention_heatmap.png",
    "baseline_ablation.png",
    "confusion_matrix_baseline.png",
    "confusion_matrix_roberta.png",
    "embedding_space_3d.png",
    "layer_probe_accuracy.png",
    "saliency_negative.png",
    "saliency_positive.png",
    "training_curves.png",
}

#: Neighbours used by the boundary-proximity reading on the embedding figure. Ten is small
#: enough to describe a local neighbourhood on 1,000 points and large enough that the
#: fraction is not decided by a single tie.
BOUNDARY_NEIGHBOURS = 10

#: "Sharply focused" on the head atlas. One nat is an effective support of e, about three
#: tokens, so a head below it is putting nearly all of its non-sink weight on a handful of
#: positions. The threshold is named rather than inlined because the figure title counts it.
FOCUSED_ENTROPY_NATS = 1.0


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _fig_confusion(matrix: np.ndarray, title: str, caption_text: str) -> Any:
    import matplotlib.pyplot as plt

    counts = np.asarray(matrix, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        normed = counts / counts.sum(axis=1, keepdims=True)
    normed = np.nan_to_num(normed)

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.7))
    for ax, data, fmt, sub, vmax in (
        (axes[0], counts, "{:.0f}", "counts", counts.max()),
        (axes[1], normed, "{:.3f}", "row-normalised (recall)", 1.0),
    ):
        im = ax.imshow(data, cmap="Blues", vmin=0, vmax=vmax)
        ax.set_xticks([0, 1], labels=[f"pred {c}" for c in CLASS_LABELS])
        ax.set_yticks([0, 1], labels=[f"true {c}" for c in CLASS_LABELS])
        ax.set_title(sub, fontsize=10, fontweight="normal")
        ax.grid(visible=False)
        for i in range(2):
            for j in range(2):
                shade = data[i, j] / (vmax if vmax else 1)
                ax.text(
                    j,
                    i,
                    fmt.format(data[i, j]),
                    ha="center",
                    va="center",
                    fontsize=11,
                    color="white" if shade > 0.55 else "#111111",
                )
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(title, fontsize=12, fontweight="bold")
    plots.caption(axes[0], caption_text)
    fig.tight_layout()
    return fig


def figure_confusion_matrices(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    written: list[Path] = []
    cfg_name = metrics["config_name"]
    pretty = {
        "tfidf_logreg": "TF-IDF + Logistic Regression (control)",
        "roberta": "RoBERTa (fine-tuned)",
    }
    filename = {"tfidf_logreg": "confusion_matrix_baseline", "roberta": "confusion_matrix_roberta"}
    for key, block in metrics["models"].items():
        if key not in filename:
            continue
        acc = block["accuracy"]
        ci = block["accuracy_ci"]
        fig = _fig_confusion(
            np.asarray(block["confusion_matrix"]),
            pretty[key],
            f"{pretty[key]} · cfg/{cfg_name}.yaml · n_test={block['n_test']} · "
            f"accuracy {acc:.4f} (Wilson 95% CI {ci['low']:.4f}-{ci['high']:.4f}) · "
            f"seed {metrics['seed']} · {metrics['device']} · this single test matrix does not "
            "support a paired model-difference claim",
        )
        plots.set_provenance(
            fig,
            {
                "accuracy": acc,
                "accuracy_ci": ci,
                "config_name": cfg_name,
                "confusion_matrix": block["confusion_matrix"],
                "model": key,
                "n_test": block["n_test"],
                "seed": metrics["seed"],
            },
        )
        written += plots.save_figure(fig, filename[key], out_dirs)
    return written


def figure_training_curves(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    import matplotlib.pyplot as plt

    block = metrics["models"].get("roberta")
    if not block:
        return []
    history = block["training"]["history"]
    if not history:
        return []

    epochs = [h["epoch"] for h in history]
    train = [h["train_loss"] for h in history]
    val = [h["val_loss"] for h in history]
    val_acc = [h["val_accuracy"] for h in history]
    epoch_ticks = [int(epoch) for epoch in epochs]

    fig, (ax, ax2) = plt.subplots(
        2,
        1,
        figsize=(9.0, 5.8),
        sharex=True,
        gridspec_kw={"height_ratios": [2.35, 1.0]},
    )
    ax.plot(
        epochs,
        train,
        marker="o",
        markersize=5.5,
        linestyle="-",
        linewidth=1.8,
        label="training loss",
        color=plots.OKABE_ITO[0],
    )
    ax.plot(
        epochs,
        val,
        marker="s",
        markersize=5.5,
        linestyle="--",
        linewidth=1.8,
        label="validation loss",
        color=plots.OKABE_ITO[1],
    )
    selected = block["training"]["selected_epoch"]
    ax.axvline(selected, linestyle="-.", linewidth=1.2, color="#555555")
    ax2.axvline(selected, linestyle="-.", linewidth=1.2, color="#555555")
    criterion = block["training"]["selection_criterion"]
    criterion_label = "lowest validation loss" if criterion == "min validation loss" else criterion
    ax.text(
        selected + 0.06,
        0.08,
        f"selected: {criterion_label}",
        transform=ax.get_xaxis_transform(),
        fontsize=8,
        color="#333333",
        ha="left",
        va="center",
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.88, "pad": 1.5},
    )
    ax.set_ylabel("loss (cross entropy)")
    ax.legend(loc="upper right")

    ax2.plot(
        epochs,
        val_acc,
        marker="^",
        markersize=5.0,
        linestyle=":",
        linewidth=1.5,
        color=plots.OKABE_ITO[2],
    )
    ax2.set_xlabel("training epoch")
    ax2.set_ylabel("validation accuracy")
    ax2.set_xticks(epoch_ticks)

    run = block["training"]
    fig.suptitle("Validation loss rose after epoch 1", fontsize=13, fontweight="bold")
    plots.caption(
        ax,
        f"cfg/{metrics['config_name']}.yaml · {block['n_train']} train / {block['n_val']} val · "
        f"seed {metrics['seed']} · {metrics['device']}, {metrics['power_mode']} · "
        f"epochs run {run['epochs_run']}/{run['epochs_configured']}"
        + (" · WALL-CLOCK CAPPED" if run["wall_clock_capped"] else "")
        + f" · epoch selected on {run['selection_criterion']} · this single training run does "
        "not support a claim about variation across seeds",
    )
    plots.set_provenance(
        fig,
        {
            "config_name": metrics["config_name"],
            "history": history,
            "model": "roberta",
            "seed": metrics["seed"],
            "selected_epoch": selected,
        },
    )
    fig.tight_layout(rect=(0, 0.03, 1, 0.96), h_pad=1.0)
    with plt.rc_context({"savefig.dpi": 160}):
        return plots.save_figure(fig, "training_curves", out_dirs)


def figure_baseline_ablation(
    metrics: dict[str, Any], out_dirs: list[Path], ablation_metrics: dict[str, Any] | None = None
) -> list[Path]:
    import matplotlib.pyplot as plt

    source = ablation_metrics or metrics
    cells = source.get("ablation") or []
    if not cells:
        return []

    labels = [c["ablation_label"] for c in cells]
    accs = [c["accuracy"] for c in cells]
    lows = [c["accuracy_ci"]["low"] for c in cells]
    highs = [c["accuracy_ci"]["high"] for c in cells]
    errs = np.array(
        [
            [a - lo for a, lo in zip(accs, lows, strict=True)],
            [hi - a for a, hi in zip(accs, highs, strict=True)],
        ]
    )
    colors = [plots.OKABE_ITO[1] if "notebook" in label else plots.OKABE_ITO[0] for label in labels]

    fig, ax = plt.subplots(figsize=(8.6, 3.9))
    y = np.arange(len(labels))
    ax.barh(
        y,
        accs,
        xerr=errs,
        color=colors,
        height=0.62,
        error_kw={"ecolor": "#444444", "capsize": 3, "lw": 1},
    )
    ax.set_yticks(y, labels=labels)
    ax.invert_yaxis()
    ax.set_xlabel("test accuracy (Wilson 95% CI)")
    roberta = metrics["models"].get("roberta")
    show_roberta = bool(roberta) and not roberta.get("random_weights", False)
    # The transformer reference line is the point of comparison, so the x-range has to
    # include it. Otherwise the axvline is drawn off-chart and silently disappears.
    right = max(highs) + 0.035
    if show_roberta:
        right = max(right, roberta["accuracy"] + 0.02)
    ax.set_xlim(max(0.0, min(lows) - 0.02), min(1.0, right))
    ax.grid(visible=True, axis="x", alpha=0.25)
    ax.grid(visible=False, axis="y")
    # Anchor the value label past the upper whisker, not at the bar end. The bar end is exactly
    # where the error bar is centred, so a label placed there covers its own whisker.
    for yi, a, high in zip(y, accs, highs, strict=True):
        ax.annotate(
            f"{a:.4f}",
            xy=(high, float(yi)),
            xytext=(5, 0),
            textcoords="offset points",
            ha="left",
            va="center",
            fontsize=9,
        )

    if show_roberta:
        ax.axvline(roberta["accuracy"], ls="--", lw=1.4, color="#111111")
        ax.annotate(
            f"fine-tuned RoBERTa\n{roberta['accuracy']:.4f}",
            xy=(roberta["accuracy"], 0.0),
            xytext=(-6, 0),
            textcoords="offset points",
            fontsize=8,
            ha="right",
            va="center",
            color="#111111",
        )

    ax.set_title("TF-IDF control: what conventional preprocessing costs")
    plots.caption(
        ax,
        f"TF-IDF + LogReg · cfg/{source['config_name']}.yaml · "
        f"n_train={cells[0]['n_train']} / n_test={cells[0]['n_test']} · seed {source['seed']} · "
        "orange = the source notebook's chain (alphanumeric-only filter + NLTK stopword removal "
        "+ Porter stemming), which deletes not/no/nor and every contraction · these test-set "
        "comparisons are post hoc and do not support confirmatory superiority claims",
    )
    plots.set_provenance(
        fig,
        {
            "ablation": [
                {
                    "accuracy": cell["accuracy"],
                    "accuracy_ci": cell["accuracy_ci"],
                    "label": cell["ablation_label"],
                }
                for cell in cells
            ],
            "config_name": source["config_name"],
            "roberta_accuracy": roberta["accuracy"] if show_roberta else None,
            "seed": source["seed"],
        },
    )
    fig.tight_layout()
    return plots.save_figure(fig, "baseline_ablation", out_dirs)


# ── model-dependent figures ──────────────────────────────────────────────────────────


def _load_model_for_figures(run_dir: Path, metrics: dict[str, Any]) -> Any:
    """Rebuild the run's transformer and load its saved weights."""
    import torch

    from cfg.schema import load_config
    from models.registry import create_model
    from models.roberta import RobertaSentiment
    from utils.device import resolve_device

    cfg = load_config(REPO_ROOT / metrics["config_path"])
    device = resolve_device(cfg.RUNTIME.DEVICE)
    # Narrowed to the concrete type: the figures need the raw nn.Module and the tokenizer,
    # neither of which belongs on the model-comparison Protocol.
    model = cast(
        RobertaSentiment,
        create_model(
            "roberta",
            pretrained=cfg.MODEL.PRETRAINED,
            revision=cfg.MODEL.REVISION,
            num_labels=cfg.MODEL.NUM_LABELS,
            max_len=cfg.MODEL.MAX_LEN,
            batch_size=cfg.MODEL.BATCH_SIZE,
            epochs=cfg.MODEL.EPOCHS,
            lr=cfg.MODEL.LR,
            seed=cfg.SEED,
            device=device,
            random_weight_layers=cfg.MODEL.RANDOM_WEIGHT_LAYERS,
        ),
    )
    ckpt = run_dir / "model_roberta.pt"
    if not ckpt.exists():
        raise FileNotFoundError(
            f"{ckpt} not found; interpretability figures need the run's weights. "
            "Re-run train.py, or pass --skip-model-figures."
        )
    state = torch.load(ckpt, map_location=device, weights_only=True)
    model.model.load_state_dict(state)
    model.model.eval()
    return model, cfg, device


def _example_texts(run_dir: Path) -> Any:
    import pandas as pd

    return pd.read_parquet(run_dir / "predictions.parquet")


def figure_attention(
    model: Any, cfg: Any, device: Any, text: str, metrics: dict[str, Any], out_dirs: list[Path]
) -> list[Path]:
    from interpretability.attention import last_layer_attention

    amap = last_layer_attention(
        model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
    )
    return _figure_attention_map(
        amap,
        metrics,
        out_dirs,
        source_row_position=NOTEBOOK_REVIEW_POSITIONS[0],
    )


def _figure_attention_map(
    amap: Any,
    metrics: dict[str, Any],
    out_dirs: list[Path],
    *,
    source_row_position: int,
) -> list[Path]:
    import matplotlib.pyplot as plt

    from interpretability.attention import pick_source_token

    # Keep the heatmap legible: the first 32 inner tokens, which is where the signal is.
    k = min(32, len(amap.tokens))
    tokens = [t.lstrip("Ġ") for t in amap.tokens[:k]]
    matrix = amap.matrix[:k, :k]

    fig, ax = plt.subplots(figsize=(8.6, 7.2))
    im = ax.imshow(matrix, cmap="magma", aspect="auto")
    ax.set_xticks(range(k), labels=tokens, rotation=90, fontsize=7)
    ax.set_yticks(range(k), labels=tokens, fontsize=7)
    ax.set_xlabel("attended-to token (key)")
    ax.set_ylabel("attending token (query)")
    ax.grid(visible=False)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03, label="attention weight")
    ax.set_title(f"Last-layer attention (layer {amap.layer}, mean over {amap.n_heads} heads)")
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · first {k} inner tokens "
        f"(<s>/</s>/<pad> excluded, since <s> is an attention sink and flattens the colour scale) · "
        f"predicted {CLASS_LABELS[amap.predicted_label]} · eager attention (sdpa returns no "
        "attentions at all on transformers 5.x) · this attention map does not support a causal "
        "explanation",
    )
    idx = pick_source_token(amap, preferred=("not", "great", "bad", "good", "no"))
    row = amap.row_for(idx)
    order = np.argsort(-row)[: min(15, row.size)]
    shared_provenance = {
        "attention_matrix": np.round(matrix, 8).tolist(),
        "checkpoint_sha256": metrics["_checkpoint_sha256"],
        "config_name": metrics["config_name"],
        "method": "last_layer_head_mean_attention",
        "model": "roberta",
        "run_git_sha": metrics["git_sha"],
        "seed": metrics["seed"],
        "source_row_position": source_row_position,
        "source_token_index": idx,
        "tokens": tokens,
        "top_target_indices": [int(value) for value in order],
    }
    plots.set_provenance(fig, shared_provenance)
    fig.tight_layout()
    written = plots.save_figure(fig, "attention_heatmap", out_dirs)

    fig2, ax2 = plt.subplots(figsize=(8.6, 3.6))
    ax2.bar(
        range(len(order)),
        row[order],
        color=plots.OKABE_ITO[0],
    )
    ax2.set_xticks(
        range(len(order)),
        labels=[amap.tokens[i].lstrip("Ġ") for i in order],
        rotation=60,
        ha="right",
    )
    ax2.set_ylabel("attention weight")
    ax2.set_xlabel("attended-to token")
    ax2.set_title(f"What '{amap.tokens[idx].lstrip('Ġ')}' attends to (top {len(order)})")
    plots.caption(
        ax2,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · source token "
        f"'{amap.tokens[idx].lstrip('Ġ')}' · last layer, head-mean · same review as the heatmap · "
        "this selected token does not support a population-level or causal importance claim",
    )
    plots.set_provenance(fig2, shared_provenance)
    fig2.tight_layout()
    written += plots.save_figure(fig2, "attention_from_token", out_dirs)
    return written


def figure_saliency(
    model: Any,
    cfg: Any,
    device: Any,
    examples: list[tuple[str, int]],
    label_name: str,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    from interpretability.saliency import gradient_saliency

    attributions = [
        gradient_saliency(
            model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
        )
        for text, _ in examples
    ]
    return _figure_saliency_attributions(
        attributions,
        [true_label for _, true_label in examples],
        label_name,
        metrics,
        out_dirs,
    )


def _figure_saliency_attributions(
    attributions: list[Any],
    true_labels: list[int],
    label_name: str,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    import matplotlib.pyplot as plt

    n = len(attributions)
    fig, axes = plt.subplots(n, 1, figsize=(9.0, 2.5 * n))
    axes_list = list(np.atleast_1d(axes))
    for ax, attr, true_label in zip(axes_list, attributions, true_labels, strict=True):
        keep = [i for i, t in enumerate(attr.tokens) if t not in {"<s>", "</s>", "<pad>"}]
        keep = keep[: min(26, len(keep))]
        toks = [attr.tokens[i].lstrip("Ġ") for i in keep]
        vals = attr.scores[keep]
        ax.bar(
            range(len(toks)),
            vals,
            color=plots.POSITIVE_COLOR if attr.predicted_label == 1 else plots.NEGATIVE_COLOR,
        )
        ax.set_xticks(range(len(toks)), labels=toks, rotation=60, ha="right", fontsize=7)
        # Short enough to stay inside its own panel: a longer label is centred over a 2.5in
        # axis and runs into the rotated tick labels of the panel above it. The quantity is
        # named in full in the figure title and the caption.
        ax.set_ylabel("Token importance", fontsize=9)
        ax.set_title(
            f"true {CLASS_LABELS[true_label]} · predicted {CLASS_LABELS[attr.predicted_label]}"
            f"{'' if attr.predicted_label == true_label else '  ← MISCLASSIFIED'}",
            fontsize=10,
            fontweight="normal",
        )
    fig.suptitle(f"Gradient-norm saliency: {label_name} reviews", fontsize=12, fontweight="bold")
    plots.caption(
        axes_list[-1],
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · gradient of the predicted-class "
        "logit w.r.t. the WORD embeddings only (the D1 fix: the notebook re-applied the full "
        "embedding module, adding position/token-type/LayerNorm twice) · this is gradient-norm "
        "saliency, NOT Grad-CAM, and it satisfies none of Integrated Gradients' axioms · "
        "these selected examples do not support a population-level prevalence claim",
    )
    plots.set_provenance(
        fig,
        {
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "example_count": len(attributions),
            "label": label_name,
            "method": "gradient_norm_saliency",
            "model": "roberta",
            "rendered_examples": [
                {
                    "logits": (
                        np.round(attr.logits, 8).tolist() if hasattr(attr, "logits") else None
                    ),
                    "predicted_label": int(attr.predicted_label),
                    "scores": np.round(attr.scores, 8).tolist(),
                    "target_label": (
                        int(attr.target_label)
                        if hasattr(attr, "target_label")
                        else int(attr.predicted_label)
                    ),
                    "tokens": list(attr.tokens),
                    "true_label": int(true_label),
                }
                for attr, true_label in zip(attributions, true_labels, strict=True)
            ],
            "run_git_sha": metrics["git_sha"],
            "seed": metrics["seed"],
        },
    )
    fig.tight_layout()
    fig.subplots_adjust(hspace=0.75)
    slug = "saliency_positive" if label_name == "positive" else "saliency_negative"
    return plots.save_figure(fig, slug, out_dirs)


# ── representation figures ───────────────────────────────────────────────────────────


def _rebuilt_splits(cfg: Any, run_dir: Path) -> Any:
    """Rebuild the run's own splits and prove the test half matches ``predictions.parquet``.

    The probe needs TRAIN rows, and a run directory holds only the test rows. The split is a
    pure function of the config and the seed, so it is rebuilt here rather than stored twice.
    That reconstruction is only trustworthy if it reproduces the half that *was* stored, so
    the test texts are compared row for row before anything is fitted.
    """
    from datasets.splits import combined_text
    from train import build_splits

    if not Path(cfg.DATA.TRAIN_PATH).is_file():
        raise FileNotFoundError(
            f"{cfg.DATA.TRAIN_PATH} not found; the layer-probe figure is fitted on the run's "
            "TRAIN rows, which live in the source parquet. Run `make data`, or pass "
            "--skip-model-figures."
        )
    splits, _ = build_splits(cfg)
    stored = [str(t) for t in _example_texts(run_dir)["text"]]
    rebuilt = [str(t) for t in combined_text(splits.test)]
    if rebuilt != stored:
        raise ValueError(
            "the rebuilt test split does not match predictions.parquet, so the rebuilt train "
            "split cannot be trusted either; refusing to fit a probe on it"
        )
    return splits


def figure_embedding_space(
    representations: Any,
    labels: np.ndarray,
    summary: Any,
    metrics: dict[str, Any],
    out_dirs: list[Path],
    *,
    embedded: np.ndarray | None = None,
) -> list[Path]:
    """Final-layer [CLS] under a 3D t-SNE, coloured by TRUE label, errors marked."""
    import matplotlib.pyplot as plt
    from sklearn.manifold import TSNE

    predicted = representations.predictions()
    correct = predicted == labels
    if embedded is None:
        embedded = TSNE(
            n_components=3,
            init="pca",
            learning_rate="auto",
            perplexity=30.0,
            random_state=int(metrics["seed"]),
        ).fit_transform(representations.final)

    fig = plt.figure(figsize=(9.0, 7.2))
    ax = fig.add_subplot(111, projection="3d")
    for value, name, colour in (
        (0, CLASS_LABELS[0], plots.NEGATIVE_COLOR),
        (1, CLASS_LABELS[1], plots.POSITIVE_COLOR),
    ):
        mask = (labels == value) & correct
        ax.scatter(
            embedded[mask, 0],
            embedded[mask, 1],
            embedded[mask, 2],
            s=11,
            alpha=0.55,
            color=colour,
            linewidths=0.0,
            label=f"true {name}, predicted correctly ({int(mask.sum())})",
        )
    for value, name, colour in (
        (0, CLASS_LABELS[0], plots.NEGATIVE_COLOR),
        (1, CLASS_LABELS[1], plots.POSITIVE_COLOR),
    ):
        mask = (labels == value) & ~correct
        ax.scatter(
            embedded[mask, 0],
            embedded[mask, 1],
            embedded[mask, 2],
            s=68,
            marker="X",
            color=colour,
            edgecolors="#111111",
            linewidths=0.9,
            label=f"true {name}, MISCLASSIFIED ({int(mask.sum())})",
        )
    ax.set_xlabel("t-SNE 1")
    ax.set_ylabel("t-SNE 2")
    ax.set_zlabel("t-SNE 3")
    ax.grid(visible=True, alpha=0.15)
    # A fixed viewpoint, so a regenerated figure is comparable to the published one rather
    # than landing wherever Matplotlib's default happens to be on the installed version.
    ax.view_init(elev=16, azim=-62)
    ax.set_box_aspect((1.0, 1.0, 0.82), zoom=1.06)
    ax.legend(loc="upper left", fontsize=8, framealpha=0.0)
    ax.set_title(
        "Errors sit inside the other class, not scattered at random",
        fontsize=12,
        fontweight="bold",
    )
    margin_correct_ci = summary.probability_margin_correct_ci
    margin_incorrect_ci = summary.probability_margin_incorrect_ci
    neighbour_correct_ci = summary.opposite_neighbours_correct_ci
    neighbour_incorrect_ci = summary.opposite_neighbours_incorrect_ci
    if (
        margin_correct_ci is not None
        and margin_incorrect_ci is not None
        and neighbour_correct_ci is not None
        and neighbour_incorrect_ci is not None
    ):
        ax.text2D(
            0.02,
            0.02,
            "95% t intervals\n"
            f"margin, correct [{margin_correct_ci[0]:.3f}, {margin_correct_ci[1]:.3f}]\n"
            f"margin, errors [{margin_incorrect_ci[0]:.3f}, {margin_incorrect_ci[1]:.3f}]\n"
            f"opposite neighbours, correct "
            f"[{100 * neighbour_correct_ci[0]:.1f}%, {100 * neighbour_correct_ci[1]:.1f}%]\n"
            f"opposite neighbours, errors "
            f"[{100 * neighbour_incorrect_ci[0]:.1f}%, {100 * neighbour_incorrect_ci[1]:.1f}%]",
            transform=ax.transAxes,
            fontsize=7.5,
            va="bottom",
            bbox={"facecolor": "white", "edgecolor": "#BBBBBB", "alpha": 0.9},
        )
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · final-layer [CLS] of all "
        f"{len(labels)} test reviews, t-SNE to 3 components, seed {metrics['seed']} · "
        f"mean predicted-probability margin |p(pos) - p(neg)| is "
        f"{summary.probability_margin_correct:.4f} on the {summary.n_correct} correct rows "
        f"against {summary.probability_margin_incorrect:.4f} on the {summary.n_incorrect} "
        "errors, with review-level 95% t intervals shown inside the plot; in the raw 768-d "
        "[CLS] space "
        f"{100 * summary.opposite_neighbours_incorrect:.1f}% of an error's "
        f"{summary.n_neighbours} nearest neighbours carry the opposite true label, against "
        f"{100 * summary.opposite_neighbours_correct:.1f}% for correct rows · t-SNE distances "
        "and cluster sizes are NOT metrically meaningful: only the neighbourhood statistics, "
        "measured before the projection, support the title · the projection does not support "
        "metric distance or cluster-size claims",
    )
    plots.set_provenance(
        fig,
        {
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "coordinates": np.round(embedded, 6).tolist(),
            "labels": [int(value) for value in labels],
            "logit_margin_correct": round(summary.logit_margin_correct, 6),
            "logit_margin_incorrect": round(summary.logit_margin_incorrect, 6),
            "method": "final_layer_cls_tsne_3d",
            "model": "roberta",
            "n_correct": summary.n_correct,
            "n_incorrect": summary.n_incorrect,
            "n_neighbours": summary.n_neighbours,
            "opposite_neighbours_correct": round(summary.opposite_neighbours_correct, 6),
            "opposite_neighbours_incorrect": round(summary.opposite_neighbours_incorrect, 6),
            "probability_margin_correct": round(summary.probability_margin_correct, 6),
            "probability_margin_correct_ci": (
                [round(value, 6) for value in margin_correct_ci]
                if margin_correct_ci is not None
                else None
            ),
            "probability_margin_incorrect": round(summary.probability_margin_incorrect, 6),
            "probability_margin_incorrect_ci": (
                [round(value, 6) for value in margin_incorrect_ci]
                if margin_incorrect_ci is not None
                else None
            ),
            "predictions": [int(value) for value in predicted],
            "opposite_neighbours_correct_ci": (
                [round(value, 6) for value in neighbour_correct_ci]
                if neighbour_correct_ci is not None
                else None
            ),
            "opposite_neighbours_incorrect_ci": (
                [round(value, 6) for value in neighbour_incorrect_ci]
                if neighbour_incorrect_ci is not None
                else None
            ),
            "run_git_sha": metrics["git_sha"],
            "seed": metrics["seed"],
        },
    )
    fig.tight_layout()
    return plots.save_figure(fig, "embedding_space_3d", out_dirs)


def figure_layer_probe(
    probes: list[Any], saturates_at: int, metrics: dict[str, Any], out_dirs: list[Path]
) -> list[Path]:
    """Linear-probe accuracy against hidden-state index: where sentiment becomes decodable."""
    import matplotlib.pyplot as plt

    layers = [probe.layer for probe in probes]
    accuracies = [probe.accuracy for probe in probes]
    intervals = [
        probe.accuracy_ci if probe.accuracy_ci is not None else (probe.accuracy, probe.accuracy)
        for probe in probes
    ]
    errors = np.asarray(
        [
            [
                accuracy - interval[0]
                for accuracy, interval in zip(accuracies, intervals, strict=True)
            ],
            [
                interval[1] - accuracy
                for accuracy, interval in zip(accuracies, intervals, strict=True)
            ],
        ]
    )
    finetuned = metrics["models"]["roberta"]["accuracy"]

    fig, ax = plt.subplots(figsize=(9.0, 4.6))
    ax.errorbar(
        layers,
        accuracies,
        yerr=errors,
        marker="o",
        markersize=5.5,
        linewidth=1.8,
        capsize=3,
        color=plots.OKABE_ITO[0],
        label="linear probe with Wilson 95% interval",
    )
    ax.axhline(0.5, ls=":", lw=1.2, color="#777777")
    ax.annotate(
        "chance",
        xy=(layers[-1], 0.5),
        xytext=(-2, 5),
        textcoords="offset points",
        ha="right",
        fontsize=8,
        color="#555555",
    )
    ax.axhline(finetuned, ls="--", lw=1.4, color="#111111")
    ax.annotate(
        f"the fine-tuned model's own test accuracy, {finetuned:.4f}",
        xy=(layers[0], finetuned),
        xytext=(2, 4),
        textcoords="offset points",
        ha="left",
        fontsize=8,
        color="#111111",
    )
    ax.axvline(saturates_at, ls="-.", lw=1.2, color="#555555")
    ax.annotate(
        f"within one point of the best probe\nfrom block {saturates_at} onward",
        xy=(saturates_at, min(accuracies) + 0.04),
        xytext=(6, 0),
        textcoords="offset points",
        ha="left",
        va="bottom",
        fontsize=8,
        color="#333333",
    )
    ax.set_xticks(layers)
    ax.set_xlabel("hidden-state index (0 = embedding output, 1-12 = encoder blocks)")
    ax.set_ylabel("test accuracy of the linear probe")
    ax.set_ylim(0.45, 1.0)
    ax.legend(loc="center right")
    ax.set_title(f"Above chance from block 1, saturated from block {saturates_at}")
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · logistic regression on the "
        f"[CLS] vector of each hidden state, standardised on train statistics · fitted on "
        f"{probes[0].n_train} TRAIN rows and scored on {probes[0].n_test} TEST rows, never "
        f"the same rows · seed {metrics['seed']} · hidden state 0 is the raw <s> embedding, "
        f"which is the same vector for every review, so its probe can only return the "
        f"majority class and {accuracies[0]:.4f} is exactly the positive rate of this test "
        "split · error bars are Wilson 95% intervals over test rows · a linear probe measures "
        "whether the label is DECODABLE from a "
        "representation; it does not support a claim that the model uses that information "
        "downstream",
    )
    plots.set_provenance(
        fig,
        {
            "accuracies": [round(value, 6) for value in accuracies],
            "accuracy_ci": [[round(value, 6) for value in interval] for interval in intervals],
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "method": "layerwise_linear_probe",
            "model": "roberta",
            "n_test": probes[0].n_test,
            "n_train": probes[0].n_train,
            "run_git_sha": metrics["git_sha"],
            "saturation_layer": saturates_at,
            "seed": metrics["seed"],
        },
    )
    fig.tight_layout()
    return plots.save_figure(fig, "layer_probe_accuracy", out_dirs)


def figure_attention_entropy_atlas(
    atlas: Any, metrics: dict[str, Any], out_dirs: list[Path]
) -> list[Path]:
    """The 12x12 head atlas: low entropy is focused attention, high entropy is diffuse."""
    import matplotlib.pyplot as plt

    focused = atlas.most_focused()
    diffuse = atlas.most_diffuse()

    n_heads_total = atlas.n_layers * atlas.n_heads
    intervals = atlas.entropy_confidence_intervals()
    if intervals is None:
        interval_low = atlas.entropy.copy()
        interval_high = atlas.entropy.copy()
    else:
        interval_low, interval_high = intervals
    interval_half_width = (interval_high - interval_low) / 2.0
    n_sharp = int((interval_high < FOCUSED_ENTROPY_NATS).sum())
    median = float(np.median(atlas.entropy))

    fig, (ax, uncertainty_ax) = plt.subplots(
        1,
        2,
        figsize=(12.6, 6.8),
        gridspec_kw={"width_ratios": [1.0, 1.0]},
    )
    image = ax.imshow(atlas.entropy, cmap="viridis", aspect="auto")
    ax.set_xticks(range(atlas.n_heads), labels=[str(h + 1) for h in range(atlas.n_heads)])
    ax.set_yticks(range(atlas.n_layers), labels=[str(v + 1) for v in range(atlas.n_layers)])
    ax.set_xlabel("attention head")
    ax.set_ylabel("encoder layer")
    ax.grid(visible=False)
    fig.colorbar(image, ax=ax, fraction=0.046, pad=0.03, label="mean attention entropy (nats)")
    uncertainty = uncertainty_ax.imshow(interval_half_width, cmap="cividis", aspect="auto")
    uncertainty_ax.set_xticks(
        range(atlas.n_heads), labels=[str(h + 1) for h in range(atlas.n_heads)]
    )
    uncertainty_ax.set_yticks(
        range(atlas.n_layers), labels=[str(v + 1) for v in range(atlas.n_layers)]
    )
    uncertainty_ax.set_xlabel("attention head")
    uncertainty_ax.set_ylabel("encoder layer")
    uncertainty_ax.set_title("95% interval half-width", fontsize=10, fontweight="normal")
    uncertainty_ax.grid(visible=False)
    fig.colorbar(
        uncertainty,
        ax=uncertainty_ax,
        fraction=0.046,
        pad=0.03,
        label="entropy interval half-width (nats)",
    )
    for coordinate, note in ((focused, "most focused"), (diffuse, "most diffuse")):
        ax.scatter(
            coordinate.head - 1,
            coordinate.layer - 1,
            s=190,
            facecolors="none",
            edgecolors="#FFFFFF",
            linewidths=2.0,
        )
        # Place the label away from the nearest edge, so a cell in the top row or the last
        # column does not push its own text off the axes and into the title.
        below = coordinate.layer <= atlas.n_layers // 2
        if coordinate.head <= 3:
            horizontal = "left"
        elif coordinate.head >= atlas.n_heads - 2:
            horizontal = "right"
        else:
            horizontal = "center"
        ax.annotate(
            f"{note}\n{coordinate.label()} · {coordinate.entropy:.3f} nats",
            xy=(coordinate.head - 1, coordinate.layer - 1),
            xytext=(0, -14 if below else 14),
            textcoords="offset points",
            ha=horizontal,
            va="top" if below else "bottom",
            fontsize=8,
            color="#111111",
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.85, "pad": 1.5},
        )
    ax.set_title(
        f"Upper 95% interval is below one nat for {n_sharp} of {n_heads_total} heads",
        fontsize=11,
    )
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · mean Shannon entropy in nats "
        f"over {atlas.n_examples} test reviews, {atlas.n_layers}x{atlas.n_heads} heads · "
        f"<s>, </s> and padding excluded on both axes and rows renormalised, so this describes "
        f"how a head spreads its non-sink attention · the attainable ceiling is "
        f"log(inner tokens), mean {atlas.mean_max_entropy:.4f} nats at "
        f"{atlas.mean_inner_tokens:.1f} inner tokens, and the median head sits at "
        f"{median:.4f} · sharply focused means the upper review-level 95% t bound is below "
        f"{FOCUSED_ENTROPY_NATS:.0f} nat, with uncertainty shown in the right panel · "
        f"{focused.label()} sends {100 * focused.sink_share:.1f}% of its mass to the excluded "
        f"tokens and {diffuse.label()} sends {100 * diffuse.sink_share:.1f}%, so neither "
        "extreme is a sink artifact · eager attention (sdpa returns no attentions at all on "
        "transformers 5.x) · this atlas does not support a causal explanation",
    )
    plots.set_provenance(
        fig,
        {
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "entropy": np.round(atlas.entropy, 8).tolist(),
            "entropy_ci_high": np.round(interval_high, 8).tolist(),
            "entropy_ci_low": np.round(interval_low, 8).tolist(),
            "max_entropy": round(float(atlas.entropy.max()), 6),
            "mean_inner_tokens": round(atlas.mean_inner_tokens, 6),
            "mean_max_entropy": round(atlas.mean_max_entropy, 6),
            "median_entropy": round(median, 6),
            "method": "attention_entropy_atlas",
            "min_entropy": round(float(atlas.entropy.min()), 6),
            "model": "roberta",
            "most_diffuse": diffuse.label(),
            "most_diffuse_sink_share": round(diffuse.sink_share, 6),
            "most_focused": focused.label(),
            "most_focused_sink_share": round(focused.sink_share, 6),
            "n_examples": atlas.n_examples,
            "n_sharply_focused": n_sharp,
            "run_git_sha": metrics["git_sha"],
            "seed": metrics["seed"],
        },
    )
    fig.tight_layout()
    return plots.save_figure(fig, "attention_entropy_atlas", out_dirs)


def figure_representations(
    model: Any,
    cfg: Any,
    device: Any,
    run_dir: Path,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    """Figures 9, 10 and 11, which share one pass over the test split."""
    from datasets.splits import combined_text
    from interpretability.representations import (
        attention_entropy_atlas,
        boundary_summary,
        cls_representations,
        layer_probe_curve,
        saturation_layer,
    )

    splits = _rebuilt_splits(cfg, run_dir)
    test_texts = [str(t) for t in combined_text(splits.test)]
    train_texts = [str(t) for t in combined_text(splits.train)]
    y_test = np.asarray([int(v) for v in splits.test["label"]], dtype=np.int64)
    y_train = [int(v) for v in splits.train["label"]]

    test_reps = cls_representations(
        model.model,
        model.tokenizer,
        test_texts,
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
        batch_size=cfg.MODEL.BATCH_SIZE,
    )
    summary = boundary_summary(test_reps, y_test, n_neighbours=BOUNDARY_NEIGHBOURS)
    written = figure_embedding_space(test_reps, y_test, summary, metrics, out_dirs)

    train_reps = cls_representations(
        model.model,
        model.tokenizer,
        train_texts,
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
        batch_size=cfg.MODEL.BATCH_SIZE,
    )
    probes = layer_probe_curve(
        train_reps.hidden, y_train, test_reps.hidden, y_test, seed=int(metrics["seed"])
    )
    written += figure_layer_probe(probes, saturation_layer(probes), metrics, out_dirs)

    atlas = attention_entropy_atlas(
        model.model, model.tokenizer, test_texts, max_len=cfg.MODEL.MAX_LEN, device=device
    )
    written += figure_attention_entropy_atlas(atlas, metrics, out_dirs)
    return written


def _selected_examples(frame: Any) -> tuple[list[tuple[str, int, int]], list[tuple[str, int, int]]]:
    positions = [position for position in NOTEBOOK_REVIEW_POSITIONS if position < len(frame)]
    rows = [
        (str(frame["text"].iloc[position]), int(frame["label"].iloc[position]), position)
        for position in positions
    ]
    positives = [row for row in rows if row[1] == 1][:3]
    negatives = [row for row in rows if row[1] == 0][:3]
    for wanted_label, bucket in ((1, positives), (0, negatives)):
        index = 0
        while len(bucket) < 3 and index < len(frame):
            if int(frame["label"].iloc[index]) == wanted_label:
                candidate = (
                    str(frame["text"].iloc[index]),
                    wanted_label,
                    index,
                )
                if candidate not in bucket:
                    bucket.append(candidate)
            index += 1
    if not rows or len(positives) != 3 or len(negatives) != 3:
        raise ValueError("the published test split cannot supply the selected figure examples")
    return positives, negatives


def _measure_model_figure_evidence(
    model: Any,
    cfg: Any,
    device: Any,
    run_dir: Path,
    metrics: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, np.ndarray]]:
    """Measure all seven model-dependent figures without retaining review text."""
    from sklearn.manifold import TSNE

    from datasets.splits import combined_text
    from interpretability.attention import last_layer_attention
    from interpretability.representations import (
        attention_entropy_atlas,
        cls_representations,
        layer_probe_curve,
        opposite_label_neighbour_fraction,
    )
    from interpretability.saliency import gradient_saliency

    frame = _example_texts(run_dir)
    positives, negatives = _selected_examples(frame)
    attention_position = NOTEBOOK_REVIEW_POSITIONS[0]
    attention_map = last_layer_attention(
        model.model,
        model.tokenizer,
        str(frame["text"].iloc[attention_position]),
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
    )
    arrays: dict[str, np.ndarray] = {
        "attention_matrix": np.asarray(attention_map.matrix, dtype=np.float32),
    }
    saliency_metadata: dict[str, list[dict[str, Any]]] = {}
    for label_name, rows in (("positive", positives), ("negative", negatives)):
        entries: list[dict[str, Any]] = []
        for index, (text, true_label, row_position) in enumerate(rows):
            attribution = gradient_saliency(
                model.model,
                model.tokenizer,
                text,
                max_len=cfg.MODEL.MAX_LEN,
                device=device,
            )
            array_name = f"saliency_{label_name}_{index}"
            arrays[array_name] = np.asarray(attribution.scores, dtype=np.float32)
            entries.append(
                {
                    "array": array_name,
                    "logits": [float(value) for value in attribution.logits],
                    "predicted_label": attribution.predicted_label,
                    "row_position": row_position,
                    "target_label": attribution.target_label,
                    "tokens": attribution.tokens,
                    "true_label": true_label,
                }
            )
        saliency_metadata[label_name] = entries

    splits = _rebuilt_splits(cfg, run_dir)
    test_texts = [str(value) for value in combined_text(splits.test)]
    train_texts = [str(value) for value in combined_text(splits.train)]
    labels = np.asarray(splits.test["label"], dtype=np.int8)
    train_labels = np.asarray(splits.train["label"], dtype=np.int8)
    test_representations = cls_representations(
        model.model,
        model.tokenizer,
        test_texts,
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
        batch_size=cfg.MODEL.BATCH_SIZE,
    )
    stored_predictions = np.asarray(frame["roberta"], dtype=np.int64)
    if not np.array_equal(test_representations.predictions(), stored_predictions):
        raise ValueError(
            "checkpoint predictions do not match predictions.parquet; refusing figure evidence"
        )
    coordinates = TSNE(
        n_components=3,
        init="pca",
        learning_rate="auto",
        perplexity=30.0,
        random_state=int(metrics["seed"]),
    ).fit_transform(test_representations.final)
    arrays.update(
        {
            "embedding_coordinates": np.asarray(coordinates, dtype=np.float32),
            "embedding_logit_margin": np.asarray(
                test_representations.logit_margin(), dtype=np.float32
            ),
            "embedding_logits": np.asarray(test_representations.logits, dtype=np.float32),
            "embedding_opposite_neighbours": np.asarray(
                opposite_label_neighbour_fraction(
                    test_representations.final,
                    labels,
                    n_neighbours=BOUNDARY_NEIGHBOURS,
                ),
                dtype=np.float32,
            ),
            "embedding_probability_margin": np.asarray(
                test_representations.probability_margin(), dtype=np.float32
            ),
            "labels": labels,
        }
    )

    train_representations = cls_representations(
        model.model,
        model.tokenizer,
        train_texts,
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
        batch_size=cfg.MODEL.BATCH_SIZE,
    )
    probes = layer_probe_curve(
        train_representations.hidden,
        train_labels,
        test_representations.hidden,
        labels,
        seed=int(metrics["seed"]),
    )
    arrays["probe_predictions"] = np.asarray([probe.predictions for probe in probes], dtype=np.int8)

    atlas = attention_entropy_atlas(
        model.model,
        model.tokenizer,
        test_texts,
        max_len=cfg.MODEL.MAX_LEN,
        device=device,
    )
    if (
        atlas.entropy_observations is None
        or atlas.sink_observations is None
        or atlas.inner_token_counts is None
    ):
        raise RuntimeError("attention atlas did not retain review-level observations")
    arrays.update(
        {
            "atlas_entropy_sum": np.asarray(
                atlas.entropy_observations.astype(np.float64).sum(axis=0),
                dtype=np.float64,
            ),
            "atlas_entropy_sum_squares": np.asarray(
                np.square(atlas.entropy_observations.astype(np.float64)).sum(axis=0),
                dtype=np.float64,
            ),
            "atlas_inner_tokens": np.asarray(atlas.inner_token_counts, dtype=np.int16),
            "atlas_sink_sum": np.asarray(
                atlas.sink_observations.astype(np.float64).sum(axis=0),
                dtype=np.float64,
            ),
        }
    )

    metadata = {
        "atlas": {"method": "review_level_head_entropy"},
        "attention": {
            "layer": attention_map.layer,
            "n_heads": attention_map.n_heads,
            "predicted_label": attention_map.predicted_label,
            "row_position": attention_position,
            "tokens": attention_map.tokens,
        },
        "embedding": {
            "method": "final_layer_cls_tsne_3d",
            "n_neighbours": BOUNDARY_NEIGHBOURS,
        },
        "probe": {
            "method": "layerwise_linear_probe",
            "n_train": len(train_labels),
        },
        "provenance": {
            "checkpoint_sha256": metrics["_checkpoint_sha256"],
            "config_name": metrics["config_name"],
            "run_git_sha": metrics["git_sha"],
            "seed": metrics["seed"],
        },
        "saliency": saliency_metadata,
    }
    return metadata, arrays


def _model_metrics_from_evidence(
    evidence: Any,
    metrics: dict[str, Any],
) -> dict[str, Any]:
    provenance = evidence.metadata.get("provenance")
    if not isinstance(provenance, dict):
        raise ValueError("model-figure evidence has no provenance")
    for field, expected in (
        ("config_name", metrics["config_name"]),
        ("run_git_sha", metrics["git_sha"]),
        ("seed", metrics["seed"]),
    ):
        if provenance.get(field) != expected:
            raise ValueError(
                f"model-figure evidence {field}={provenance.get(field)!r}, expected {expected!r}"
            )
    return {
        **metrics,
        "_checkpoint_sha256": provenance["checkpoint_sha256"],
    }


def _render_model_figure_evidence(
    evidence: Any,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    """Regenerate all seven model-dependent figures from compact committed evidence."""
    from statsmodels.stats.proportion import proportion_confint

    from interpretability.attention import AttentionMap
    from interpretability.representations import (
        AttentionAtlas,
        LayerProbe,
        boundary_summary_from_observations,
        saturation_layer,
    )
    from interpretability.saliency import TokenAttribution

    arrays = evidence.arrays
    model_metrics = _model_metrics_from_evidence(evidence, metrics)
    attention = evidence.metadata["attention"]
    attention_map = AttentionMap(
        tokens=[str(value) for value in attention["tokens"]],
        matrix=arrays["attention_matrix"],
        layer=int(attention["layer"]),
        n_heads=int(attention["n_heads"]),
        predicted_label=int(attention["predicted_label"]),
    )
    written = _figure_attention_map(
        attention_map,
        model_metrics,
        out_dirs,
        source_row_position=int(attention["row_position"]),
    )

    for label_name in ("positive", "negative"):
        attributions: list[TokenAttribution] = []
        true_labels: list[int] = []
        for entry in evidence.metadata["saliency"][label_name]:
            attributions.append(
                TokenAttribution(
                    tokens=[str(value) for value in entry["tokens"]],
                    scores=arrays[entry["array"]],
                    predicted_label=int(entry["predicted_label"]),
                    target_label=int(entry["target_label"]),
                    logits=np.asarray(entry["logits"], dtype=np.float32),
                )
            )
            true_labels.append(int(entry["true_label"]))
        written += _figure_saliency_attributions(
            attributions,
            true_labels,
            label_name,
            model_metrics,
            out_dirs,
        )

    labels = arrays["labels"].astype(np.int64)
    logits = arrays["embedding_logits"]
    predictions = logits.argmax(axis=1)
    summary = boundary_summary_from_observations(
        labels,
        predictions,
        arrays["embedding_probability_margin"],
        arrays["embedding_logit_margin"],
        arrays["embedding_opposite_neighbours"],
        n_neighbours=int(evidence.metadata["embedding"]["n_neighbours"]),
    )
    from interpretability.representations import ClsRepresentations

    representations = ClsRepresentations(
        hidden=np.zeros((1, len(labels), 1), dtype=np.float32),
        logits=logits,
    )
    written += figure_embedding_space(
        representations,
        labels,
        summary,
        model_metrics,
        out_dirs,
        embedded=arrays["embedding_coordinates"],
    )

    probe_predictions = arrays["probe_predictions"].astype(np.int64)
    probes: list[LayerProbe] = []
    for layer, predicted in enumerate(probe_predictions):
        correct = int((predicted == labels).sum())
        low, high = proportion_confint(correct, len(labels), method="wilson")
        probes.append(
            LayerProbe(
                layer=layer,
                accuracy=correct / len(labels),
                n_train=int(evidence.metadata["probe"]["n_train"]),
                n_test=len(labels),
                predictions=tuple(int(value) for value in predicted),
                accuracy_ci=(float(low), float(high)),
            )
        )
    written += figure_layer_probe(
        probes,
        saturation_layer(probes),
        model_metrics,
        out_dirs,
    )

    entropy_sum = arrays["atlas_entropy_sum"]
    entropy_sum_squares = arrays["atlas_entropy_sum_squares"]
    sink_sum = arrays["atlas_sink_sum"]
    inner_token_counts = arrays["atlas_inner_tokens"]
    n_examples = len(inner_token_counts)
    atlas = AttentionAtlas(
        entropy=entropy_sum / n_examples,
        sink_share=sink_sum / n_examples,
        n_examples=n_examples,
        mean_inner_tokens=float(inner_token_counts.mean()),
        mean_max_entropy=float(np.log(inner_token_counts.astype(np.float64)).mean()),
        inner_token_counts=inner_token_counts,
        entropy_sum_squares=entropy_sum_squares,
    )
    written += figure_attention_entropy_atlas(atlas, model_metrics, out_dirs)
    return written


def _preflight(
    run_dir: Path,
    metrics: dict[str, Any],
    ablation_run_dir: Path | None,
    *,
    skip_model_figures: bool,
    require_live_model: bool,
) -> dict[str, Any] | None:
    """Validate every required input before the first PNG can be written."""
    if skip_model_figures:
        return (
            read_json(ablation_run_dir / "metrics.json") if ablation_run_dir is not None else None
        )

    if require_live_model:
        for required in ("model_roberta.pt", "predictions.parquet"):
            path = run_dir / required
            if not path.is_file():
                raise FileNotFoundError(
                    f"{path} not found; live model evidence requires the published "
                    "checkpoint and paired predictions"
                )
    roberta = metrics.get("models", {}).get("roberta")
    if not roberta or not roberta.get("training", {}).get("history"):
        raise ValueError(
            f"{run_dir / 'metrics.json'} has no fine-tuned RoBERTa training history; "
            "refusing to produce a partial publication set"
        )
    if ablation_run_dir is None:
        raise ValueError(
            "a complete eleven-figure export requires --ablation-run-dir "
            "(the published target uses runs/run_3)"
        )
    ablation_path = ablation_run_dir / "metrics.json"
    if not ablation_path.is_file():
        raise FileNotFoundError(
            f"{ablation_path} not found; the baseline ablation figure cannot be generated"
        )
    ablation_metrics = read_json(ablation_path)
    if len(ablation_metrics.get("ablation") or []) != 4:
        raise ValueError(
            f"{ablation_path} does not contain the required four-cell ablation; "
            "refusing to produce a partial publication set"
        )
    return ablation_metrics


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("-i", "--run-dir", type=Path, default=REPO_ROOT / "runs" / "latest")
    ap.add_argument("-o", "--out-dir", type=Path, default=REPO_ROOT / "docs" / "images")
    ap.add_argument(
        "-a",
        "--ablation-run-dir",
        type=Path,
        default=None,
        help="run dir holding the ablation cells, if a different run produced them",
    )
    ap.add_argument("--skip-model-figures", action="store_true", help="metric figures only")
    evidence_group = ap.add_mutually_exclusive_group()
    evidence_group.add_argument(
        "--model-evidence",
        type=Path,
        help="committed model_figures.json used to regenerate the seven model figures",
    )
    evidence_group.add_argument(
        "--write-model-evidence",
        type=Path,
        help="measure live weights, write model figure evidence, then render from it",
    )
    ap.add_argument(
        "--publish",
        action="store_true",
        help="also mirror the requested output into tracked reports/figures (explicit opt-in)",
    )
    ap.add_argument("--show", action="store_true", help="also display interactively (never in CI)")
    args = ap.parse_args(argv)

    run_dir = args.run_dir.resolve()
    metrics = read_json(run_dir / "metrics.json")
    ablation_run_dir = args.ablation_run_dir.resolve() if args.ablation_run_dir else None
    ablation_metrics = _preflight(
        run_dir,
        metrics,
        ablation_run_dir,
        skip_model_figures=args.skip_model_figures,
        require_live_model=args.model_evidence is None,
    )
    out_dirs = [args.out_dir.resolve()]
    if args.publish:
        publication_dir = (REPO_ROOT / "reports" / "figures").resolve()
        if publication_dir not in out_dirs:
            out_dirs.append(publication_dir)

    plots.apply_style()
    if args.show:  # pragma: no cover - interactive only
        plots.enable_interactive()

    written: list[Path] = []
    written += figure_confusion_matrices(metrics, out_dirs)
    written += figure_training_curves(metrics, out_dirs)
    written += figure_baseline_ablation(metrics, out_dirs, ablation_metrics)

    if not args.skip_model_figures and args.model_evidence is not None:
        from scripts.model_figure_evidence import load_model_figure_evidence

        evidence = load_model_figure_evidence(args.model_evidence.resolve())
        written += _render_model_figure_evidence(evidence, metrics, out_dirs)
    elif not args.skip_model_figures and args.write_model_evidence is not None:
        from scripts.model_figure_evidence import (
            load_model_figure_evidence,
            write_model_figure_evidence,
        )

        model, cfg, device = _load_model_for_figures(run_dir, metrics)
        model_metrics = {
            **metrics,
            "_checkpoint_sha256": _sha256(run_dir / "model_roberta.pt"),
        }
        metadata, arrays = _measure_model_figure_evidence(
            model,
            cfg,
            device,
            run_dir,
            model_metrics,
        )
        evidence_path = args.write_model_evidence.resolve()
        write_model_figure_evidence(evidence_path, metadata, arrays)
        evidence = load_model_figure_evidence(evidence_path)
        written += _render_model_figure_evidence(evidence, metrics, out_dirs)
    elif not args.skip_model_figures:
        model, cfg, device = _load_model_for_figures(run_dir, metrics)
        model_metrics = {
            **metrics,
            "_checkpoint_sha256": _sha256(run_dir / "model_roberta.pt"),
        }
        frame = _example_texts(run_dir)
        selected_positives, selected_negatives = _selected_examples(frame)
        positives = [(text, label) for text, label, _ in selected_positives]
        negatives = [(text, label) for text, label, _ in selected_negatives]

        written += figure_attention(
            model,
            cfg,
            device,
            str(frame["text"].iloc[NOTEBOOK_REVIEW_POSITIONS[0]]),
            model_metrics,
            out_dirs,
        )
        written += figure_saliency(
            model, cfg, device, positives, "positive", model_metrics, out_dirs
        )
        written += figure_saliency(
            model, cfg, device, negatives, "negative", model_metrics, out_dirs
        )
        written += figure_representations(model, cfg, device, run_dir, model_metrics, out_dirs)

    unique_names = sorted({p.name for p in written})
    if not args.skip_model_figures and set(unique_names) != EXPECTED_FIGURES:
        missing = sorted(EXPECTED_FIGURES - set(unique_names))
        extra = sorted(set(unique_names) - EXPECTED_FIGURES)
        raise RuntimeError(
            f"figure export was incomplete: missing={missing or 'none'}, extra={extra or 'none'}"
        )
    print(f"==> wrote {len(unique_names)} distinct figures into {len(out_dirs)} directories")
    for name in unique_names:
        print(f"    {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
