#!/usr/bin/env python
"""THE figure generator. Every PNG in ``docs/images/`` comes from this file.

Nothing in this repo is hand-exported: if a figure cannot be regenerated by one command it
does not ship. ``make figures`` runs this against ``runs/latest``.

Eight figures:

===============================  ============================================================
``confusion_matrix_baseline``    TF-IDF + LogReg, counts and row-normalised side by side
``confusion_matrix_roberta``     fine-tuned RoBERTa, same layout
``training_curves``              per-epoch train and **validation** loss (justifies D4)
``attention_heatmap``            last-layer head-mean attention, inner tokens only
``attention_from_token``         what one chosen source token attends to
``saliency_positive``            gradient-norm saliency, 3 positive reviews, post-D1-fix
``saliency_negative``            gradient-norm saliency, 3 negative reviews, post-D1-fix
``baseline_ablation``            the 2x2 preprocessing grid
===============================  ============================================================

Every caption names the model and the config that produced it, because a figure whose
provenance is unstated is indistinguishable from a figure taken from somewhere else.

The interpretability figures need live weights, so they are regenerated by re-fitting on the
run's own seed and config. When the checkpoint saved by ``train.py`` is present it is loaded
instead — no retraining. Pass ``--skip-model-figures`` to produce only the metric figures.

Usage
-----
    uv run python scripts/export_figures.py -i runs/latest -o docs/images
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from utils import plots  # noqa: E402
from utils.runs import read_json  # noqa: E402

#: The exact review positions the source notebook hand-picked, so the notebook and the README
#: discuss the same six examples. Positions are into the run's test split.
NOTEBOOK_REVIEW_POSITIONS = (5, 7, 9, 11, 13, 16)

CLASS_LABELS = ("negative", "positive")


def _fig_confusion(
    matrix: np.ndarray, title: str, caption_text: str
) -> Any:
    import matplotlib.pyplot as plt

    counts = np.asarray(matrix, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        normed = counts / counts.sum(axis=1, keepdims=True)
    normed = np.nan_to_num(normed)

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.7))
    for ax, data, fmt, sub, vmax in (
        (axes[0], counts, "{:.0f}", "counts", counts.max()),
        (axes[1], normed, "{:.3f}", "row-normalised (recall)", 1.0),
    ):
        im = ax.imshow(data, cmap="Blues", vmin=0, vmax=vmax)
        ax.set_xticks([0, 1], labels=[f"pred {c}" for c in CLASS_LABELS])
        ax.set_yticks([0, 1], labels=[f"true {c}" for c in CLASS_LABELS])
        ax.set_title(sub, fontsize=10, fontweight="normal")
        ax.grid(visible=False)
        for i in range(2):
            for j in range(2):
                shade = data[i, j] / (vmax if vmax else 1)
                ax.text(
                    j,
                    i,
                    fmt.format(data[i, j]),
                    ha="center",
                    va="center",
                    fontsize=11,
                    color="white" if shade > 0.55 else "#111111",
                )
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(title, fontsize=12, fontweight="bold")
    plots.caption(axes[0], caption_text)
    fig.tight_layout()
    return fig


def figure_confusion_matrices(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    written: list[Path] = []
    cfg_name = metrics["config_name"]
    pretty = {
        "tfidf_logreg": "TF-IDF + Logistic Regression (control)",
        "roberta": "RoBERTa (fine-tuned)",
    }
    filename = {"tfidf_logreg": "confusion_matrix_baseline", "roberta": "confusion_matrix_roberta"}
    for key, block in metrics["models"].items():
        if key not in filename:
            continue
        acc = block["accuracy"]
        ci = block["accuracy_ci"]
        fig = _fig_confusion(
            np.asarray(block["confusion_matrix"]),
            pretty[key],
            f"{pretty[key]} · cfg/{cfg_name}.yaml · n_test={block['n_test']} · "
            f"accuracy {acc:.4f} (Wilson 95% CI {ci['low']:.4f}-{ci['high']:.4f}) · "
            f"seed {metrics['seed']} · {metrics['device']}",
        )
        written += plots.save_figure(fig, filename[key], out_dirs)
    return written


def figure_training_curves(metrics: dict[str, Any], out_dirs: list[Path]) -> list[Path]:
    import matplotlib.pyplot as plt

    block = metrics["models"].get("roberta")
    if not block:
        return []
    history = block["training"]["history"]
    if not history:
        return []

    epochs = [h["epoch"] for h in history]
    train = [h["train_loss"] for h in history]
    val = [h["val_loss"] for h in history]
    val_acc = [h["val_accuracy"] for h in history]

    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(9.0, 3.6))
    ax.plot(epochs, train, marker="o", label="train loss", color=plots.OKABE_ITO[0])
    ax.plot(epochs, val, marker="s", label="validation loss", color=plots.OKABE_ITO[1])
    selected = block["training"]["selected_epoch"]
    ax.axvline(selected, ls="--", lw=1.1, color="#666666")
    ax.annotate(
        f"selected epoch {selected}",
        xy=(selected, max(max(train), max(val))),
        xytext=(4, -8),
        textcoords="offset points",
        fontsize=8,
        color="#444444",
    )
    ax.set_xlabel("epoch")
    ax.set_ylabel("cross-entropy loss")
    ax.set_title("loss per epoch")
    ax.set_xticks(epochs)
    ax.legend()

    ax2.plot(epochs, val_acc, marker="o", color=plots.OKABE_ITO[2])
    ax2.set_xlabel("epoch")
    ax2.set_ylabel("validation accuracy")
    ax2.set_title("validation accuracy per epoch")
    ax2.set_xticks(epochs)

    run = block["training"]
    fig.suptitle("RoBERTa fine-tuning — train vs validation", fontsize=12, fontweight="bold")
    plots.caption(
        ax,
        f"cfg/{metrics['config_name']}.yaml · {block['n_train']} train / {block['n_val']} val · "
        f"seed {metrics['seed']} · {metrics['device']}, {metrics['power_mode']} · "
        f"epochs run {run['epochs_run']}/{run['epochs_configured']}"
        + (" · WALL-CLOCK CAPPED" if run["wall_clock_capped"] else "")
        + f" · epoch selected on {run['selection_criterion']}",
    )
    fig.tight_layout()
    return plots.save_figure(fig, "training_curves", out_dirs)


def figure_baseline_ablation(
    metrics: dict[str, Any], out_dirs: list[Path], ablation_metrics: dict[str, Any] | None = None
) -> list[Path]:
    import matplotlib.pyplot as plt

    source = ablation_metrics or metrics
    cells = source.get("ablation") or []
    if not cells:
        return []

    labels = [c["ablation_label"] for c in cells]
    accs = [c["accuracy"] for c in cells]
    lows = [c["accuracy_ci"]["low"] for c in cells]
    highs = [c["accuracy_ci"]["high"] for c in cells]
    errs = np.array([[a - lo for a, lo in zip(accs, lows, strict=True)], [hi - a for a, hi in zip(accs, highs, strict=True)]])
    colors = [plots.OKABE_ITO[1] if "notebook" in label else plots.OKABE_ITO[0] for label in labels]

    fig, ax = plt.subplots(figsize=(8.6, 3.9))
    y = np.arange(len(labels))
    ax.barh(y, accs, xerr=errs, color=colors, height=0.62, error_kw={"ecolor": "#444444", "capsize": 3, "lw": 1})
    ax.set_yticks(y, labels=labels)
    ax.invert_yaxis()
    ax.set_xlabel("test accuracy (Wilson 95% CI)")
    lo = min(lows) - 0.02
    ax.set_xlim(max(0.0, lo), min(1.0, max(highs) + 0.02))
    ax.grid(visible=True, axis="x", alpha=0.25)
    ax.grid(visible=False, axis="y")
    for yi, a in zip(y, accs, strict=True):
        ax.text(a, yi, f"  {a:.4f}", va="center", fontsize=9)

    roberta = metrics["models"].get("roberta")
    if roberta and not roberta.get("random_weights", False):
        ax.axvline(roberta["accuracy"], ls="--", lw=1.2, color="#111111")
        ax.annotate(
            f"fine-tuned RoBERTa {roberta['accuracy']:.4f}",
            xy=(roberta["accuracy"], len(labels) - 0.4),
            xytext=(-4, 0),
            textcoords="offset points",
            fontsize=8,
            ha="right",
            color="#111111",
        )

    ax.set_title("TF-IDF control: what conventional preprocessing costs")
    plots.caption(
        ax,
        f"TF-IDF + LogReg · cfg/{source['config_name']}.yaml · "
        f"n_train={cells[0]['n_train']} / n_test={cells[0]['n_test']} · seed {source['seed']} · "
        "orange = the source notebook's chain (alphanumeric-only filter + NLTK stopword removal "
        "+ Porter stemming), which deletes not/no/nor and every contraction",
    )
    fig.tight_layout()
    return plots.save_figure(fig, "baseline_ablation", out_dirs)


# ── model-dependent figures ──────────────────────────────────────────────────────────


def _load_model_for_figures(run_dir: Path, metrics: dict[str, Any]) -> Any:
    """Rebuild the run's transformer and load its saved weights."""
    import torch

    from cfg.schema import load_config
    from models.registry import create_model
    from utils.device import resolve_device

    cfg = load_config(REPO_ROOT / metrics["config_path"])
    device = resolve_device(cfg.RUNTIME.DEVICE)
    model = create_model(
        "roberta",
        pretrained=cfg.MODEL.PRETRAINED,
        num_labels=cfg.MODEL.NUM_LABELS,
        max_len=cfg.MODEL.MAX_LEN,
        batch_size=cfg.MODEL.BATCH_SIZE,
        epochs=cfg.MODEL.EPOCHS,
        lr=cfg.MODEL.LR,
        seed=cfg.SEED,
        device=device,
        random_weight_layers=cfg.MODEL.RANDOM_WEIGHT_LAYERS,
    )
    ckpt = run_dir / "model_roberta.pt"
    if not ckpt.exists():
        raise FileNotFoundError(
            f"{ckpt} not found — interpretability figures need the run's weights. "
            "Re-run train.py, or pass --skip-model-figures."
        )
    state = torch.load(ckpt, map_location=device, weights_only=True)
    model.model.load_state_dict(state)
    model.model.eval()
    return model, cfg, device


def _example_texts(run_dir: Path) -> "Any":
    import pandas as pd

    return pd.read_parquet(run_dir / "predictions.parquet")


def figure_attention(
    model: Any, cfg: Any, device: Any, text: str, metrics: dict[str, Any], out_dirs: list[Path]
) -> list[Path]:
    import matplotlib.pyplot as plt

    from interpretability.attention import last_layer_attention, pick_source_token

    amap = last_layer_attention(
        model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
    )
    # Keep the heatmap legible: the first 32 inner tokens, which is where the signal is.
    k = min(32, len(amap.tokens))
    tokens = [t.lstrip("Ġ") for t in amap.tokens[:k]]
    matrix = amap.matrix[:k, :k]

    fig, ax = plt.subplots(figsize=(8.6, 7.2))
    im = ax.imshow(matrix, cmap="magma", aspect="auto")
    ax.set_xticks(range(k), labels=tokens, rotation=90, fontsize=7)
    ax.set_yticks(range(k), labels=tokens, fontsize=7)
    ax.set_xlabel("attended-to token (key)")
    ax.set_ylabel("attending token (query)")
    ax.grid(visible=False)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03, label="attention weight")
    ax.set_title(f"Last-layer attention (layer {amap.layer}, mean over {amap.n_heads} heads)")
    plots.caption(
        ax,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · first {k} inner tokens "
        f"(<s>/</s>/<pad> excluded — <s> is an attention sink and flattens the colour scale) · "
        f"predicted {CLASS_LABELS[amap.predicted_label]} · eager attention (sdpa returns no "
        "attentions at all on transformers 5.x) · attention is not causal explanation",
    )
    fig.tight_layout()
    written = plots.save_figure(fig, "attention_heatmap", out_dirs)

    idx = pick_source_token(amap, preferred=("not", "great", "bad", "good", "no"))
    row = amap.row_for(idx)
    order = np.argsort(-row)[: min(15, row.size)]
    fig2, ax2 = plt.subplots(figsize=(8.6, 3.6))
    ax2.bar(
        range(len(order)),
        row[order],
        color=plots.OKABE_ITO[0],
    )
    ax2.set_xticks(range(len(order)), labels=[amap.tokens[i].lstrip("Ġ") for i in order], rotation=60, ha="right")
    ax2.set_ylabel("attention weight")
    ax2.set_xlabel("attended-to token")
    ax2.set_title(f"What '{amap.tokens[idx].lstrip('Ġ')}' attends to (top {len(order)})")
    plots.caption(
        ax2,
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · source token "
        f"'{amap.tokens[idx].lstrip('Ġ')}' · last layer, head-mean · same review as the heatmap",
    )
    fig2.tight_layout()
    written += plots.save_figure(fig2, "attention_from_token", out_dirs)
    return written


def figure_saliency(
    model: Any,
    cfg: Any,
    device: Any,
    examples: list[tuple[str, int]],
    label_name: str,
    metrics: dict[str, Any],
    out_dirs: list[Path],
) -> list[Path]:
    import matplotlib.pyplot as plt

    from interpretability.saliency import gradient_saliency

    n = len(examples)
    fig, axes = plt.subplots(n, 1, figsize=(9.0, 2.5 * n))
    axes_list = list(np.atleast_1d(axes))
    for ax, (text, true_label) in zip(axes_list, examples, strict=True):
        attr = gradient_saliency(
            model.model, model.tokenizer, text, max_len=cfg.MODEL.MAX_LEN, device=device
        )
        keep = [i for i, t in enumerate(attr.tokens) if t not in {"<s>", "</s>", "<pad>"}]
        keep = keep[: min(26, len(keep))]
        toks = [attr.tokens[i].lstrip("Ġ") for i in keep]
        vals = attr.scores[keep]
        ax.bar(
            range(len(toks)),
            vals,
            color=plots.POSITIVE_COLOR if attr.predicted_label == 1 else plots.NEGATIVE_COLOR,
        )
        ax.set_xticks(range(len(toks)), labels=toks, rotation=60, ha="right", fontsize=7)
        ax.set_ylabel("‖∂logit/∂emb‖₂")
        ax.set_title(
            f"true {CLASS_LABELS[true_label]} · predicted {CLASS_LABELS[attr.predicted_label]}"
            f"{'' if attr.predicted_label == true_label else '  ← MISCLASSIFIED'}",
            fontsize=10,
            fontweight="normal",
        )
    fig.suptitle(f"Gradient-norm saliency — {label_name} reviews", fontsize=12, fontweight="bold")
    plots.caption(
        axes_list[-1],
        f"RoBERTa fine-tuned, cfg/{metrics['config_name']}.yaml · gradient of the predicted-class "
        "logit w.r.t. the WORD embeddings only (the D1 fix: the notebook re-applied the full "
        "embedding module, adding position/token-type/LayerNorm twice) · this is gradient-norm "
        "saliency, NOT Grad-CAM, and it satisfies none of Integrated Gradients' axioms",
    )
    fig.tight_layout()
    slug = "saliency_positive" if label_name == "positive" else "saliency_negative"
    return plots.save_figure(fig, slug, out_dirs)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-i", "--run-dir", type=Path, default=REPO_ROOT / "runs" / "latest")
    ap.add_argument("-o", "--out-dir", type=Path, default=REPO_ROOT / "docs" / "images")
    ap.add_argument(
        "-a",
        "--ablation-run-dir",
        type=Path,
        default=None,
        help="run dir holding the ablation cells, if a different run produced them",
    )
    ap.add_argument("--skip-model-figures", action="store_true", help="metric figures only")
    ap.add_argument("--show", action="store_true", help="also display interactively (never in CI)")
    args = ap.parse_args(argv)

    plots.apply_style()
    if args.show:  # pragma: no cover - interactive only
        plots.enable_interactive()

    run_dir = args.run_dir.resolve()
    metrics = read_json(run_dir / "metrics.json")
    out_dirs = [args.out_dir, run_dir / "figures", REPO_ROOT / "reports" / "figures"]

    written: list[Path] = []
    written += figure_confusion_matrices(metrics, out_dirs)
    written += figure_training_curves(metrics, out_dirs)

    ablation_metrics = (
        read_json(args.ablation_run_dir.resolve() / "metrics.json") if args.ablation_run_dir else None
    )
    written += figure_baseline_ablation(metrics, out_dirs, ablation_metrics)

    if not args.skip_model_figures:
        model, cfg, device = _load_model_for_figures(run_dir, metrics)
        frame = _example_texts(run_dir)
        positions = [p for p in NOTEBOOK_REVIEW_POSITIONS if p < len(frame)]
        rows = [(str(frame["text"].iloc[p]), int(frame["label"].iloc[p])) for p in positions]
        positives = [r for r in rows if r[1] == 1][:3]
        negatives = [r for r in rows if r[1] == 0][:3]
        # Backfill from the split if the notebook's six positions are lopsided in this run.
        for want, bucket in ((1, positives), (0, negatives)):
            i = 0
            while len(bucket) < 3 and i < len(frame):
                if int(frame["label"].iloc[i]) == want:
                    candidate = (str(frame["text"].iloc[i]), want)
                    if candidate not in bucket:
                        bucket.append(candidate)
                i += 1

        written += figure_attention(model, cfg, device, rows[0][0], metrics, out_dirs)
        written += figure_saliency(model, cfg, device, positives, "positive", metrics, out_dirs)
        written += figure_saliency(model, cfg, device, negatives, "negative", metrics, out_dirs)

    unique_names = sorted({p.name for p in written})
    print(f"==> wrote {len(unique_names)} distinct figures into {len(out_dirs)} directories")
    for name in unique_names:
        print(f"    {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
